/**
 * emoji.ts — curated emoji dataset for the chat composer's picker.
 *
 * Self-contained (no dependency / no network): a hand-picked set of common
 * emojis grouped into categories, each with localized (en/zh/ja) search
 * keywords. The picker browses by category when the search box is empty and
 * filters across all three languages (or by a direct character match) otherwise;
 * the hover tooltip shows the keywords for the active locale.
 */

/** Per-locale, space-separated search terms. */
export interface EmojiKeywords {
  en: string
  zh: string
  ja: string
}

export interface Emoji {
  char: string
  keywords: EmojiKeywords
}

export interface EmojiGroup {
  /** A representative emoji used as the section's heading icon. */
  icon: string
  emojis: Emoji[]
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    icon: '😀',
    emojis: [
      { char: '😀', keywords: { en: 'grinning happy smile', zh: '笑 开心 微笑', ja: '笑顔 にっこり 嬉しい' } },
      { char: '😄', keywords: { en: 'happy smile joy', zh: '开心 笑 高兴', ja: '笑顔 嬉しい 喜び' } },
      { char: '😁', keywords: { en: 'grin beaming', zh: '咧嘴笑 露齿笑', ja: 'にっこり 歯を見せる' } },
      { char: '😆', keywords: { en: 'laugh haha', zh: '大笑 哈哈', ja: '大笑い わはは' } },
      { char: '😅', keywords: { en: 'sweat nervous laugh', zh: '苦笑 冷汗 尴尬', ja: '苦笑い 汗' } },
      { char: '🤣', keywords: { en: 'rofl rolling laughing', zh: '爆笑 笑翻 打滚笑', ja: '爆笑 大笑い' } },
      { char: '😂', keywords: { en: 'joy tears laugh cry', zh: '笑哭 喜极而泣', ja: '笑い泣き 涙' } },
      { char: '🙂', keywords: { en: 'slight smile', zh: '微笑', ja: '微笑み' } },
      { char: '😉', keywords: { en: 'wink', zh: '眨眼', ja: 'ウインク' } },
      { char: '😊', keywords: { en: 'blush smile happy', zh: '害羞 微笑 开心', ja: '照れ 微笑み' } },
      { char: '😍', keywords: { en: 'heart eyes love', zh: '花痴 喜欢 爱心眼', ja: 'ハート目 大好き' } },
      { char: '🥰', keywords: { en: 'love adore hearts', zh: '爱慕 喜欢 幸福', ja: '愛おしい 幸せ' } },
      { char: '😘', keywords: { en: 'kiss blow', zh: '飞吻 亲吻', ja: '投げキス キス' } },
      { char: '😋', keywords: { en: 'yum tasty delicious', zh: '好吃 美味 馋', ja: '美味しい よだれ' } },
      { char: '😜', keywords: { en: 'wink tongue silly', zh: '吐舌 调皮 眨眼', ja: '舌出し おどけ' } },
      { char: '🤪', keywords: { en: 'zany crazy goofy', zh: '疯狂 搞怪', ja: 'おちゃらけ 変顔' } },
      { char: '🤔', keywords: { en: 'thinking hmm', zh: '思考 想', ja: '考え中 うーん' } },
      { char: '🤗', keywords: { en: 'hug hugging', zh: '抱抱 拥抱', ja: 'ハグ 抱きしめ' } },
      { char: '🤫', keywords: { en: 'shush quiet secret', zh: '嘘 安静 保密', ja: 'しーっ 静かに 秘密' } },
      { char: '😐', keywords: { en: 'neutral meh', zh: '面无表情 无语', ja: '無表情 真顔' } },
      { char: '😏', keywords: { en: 'smirk', zh: '得意 坏笑', ja: 'にやり ドヤ' } },
      { char: '😴', keywords: { en: 'sleep zzz tired', zh: '睡觉 困', ja: '寝る 眠い' } },
      { char: '😭', keywords: { en: 'sob cry loudly', zh: '大哭 嚎啕', ja: '大泣き 号泣' } },
      { char: '😢', keywords: { en: 'cry sad tear', zh: '哭 难过 流泪', ja: '泣く 悲しい 涙' } },
      { char: '😡', keywords: { en: 'angry mad rage', zh: '生气 愤怒', ja: '怒り 激怒' } },
      { char: '😱', keywords: { en: 'scream shock fear', zh: '尖叫 震惊 害怕', ja: '悲鳴 ショック' } },
      { char: '🥳', keywords: { en: 'party celebrate hat', zh: '庆祝 派对 生日', ja: 'お祝い パーティー' } },
      { char: '😎', keywords: { en: 'cool sunglasses', zh: '酷 墨镜', ja: 'かっこいい サングラス' } },
      { char: '🤓', keywords: { en: 'nerd geek glasses', zh: '书呆子 极客 眼镜', ja: 'オタク メガネ' } },
      { char: '🥺', keywords: { en: 'pleading puppy eyes', zh: '可怜 委屈 求', ja: 'うるうる お願い' } },
      { char: '😬', keywords: { en: 'grimace awkward', zh: '尴尬 龇牙', ja: '気まずい 引きつり' } },
      { char: '🙄', keywords: { en: 'eye roll', zh: '翻白眼 无奈', ja: '白目 やれやれ' } },
      { char: '😤', keywords: { en: 'huff triumph proud', zh: '哼 得意 不服', ja: 'ふんっ 鼻息' } },
      { char: '🤯', keywords: { en: 'mind blown shocked', zh: '震惊 脑袋爆炸', ja: '衝撃 頭爆発' } },
      { char: '🥵', keywords: { en: 'hot sweating heat', zh: '热 中暑', ja: '暑い 汗だく' } },
      { char: '🥶', keywords: { en: 'cold freezing', zh: '冷 冻', ja: '寒い 凍える' } },
      { char: '😇', keywords: { en: 'angel innocent halo', zh: '天使 无辜', ja: '天使 純真' } },
      { char: '🤡', keywords: { en: 'clown', zh: '小丑', ja: 'ピエロ 道化' } },
      { char: '💀', keywords: { en: 'skull dead', zh: '骷髅 死', ja: 'ドクロ 死' } },
      { char: '👻', keywords: { en: 'ghost boo', zh: '幽灵 鬼', ja: '幽霊 お化け' } },
      { char: '👽', keywords: { en: 'alien ufo', zh: '外星人', ja: '宇宙人 エイリアン' } },
      { char: '🤖', keywords: { en: 'robot bot', zh: '机器人', ja: 'ロボット' } },
      { char: '💩', keywords: { en: 'poop pile', zh: '便便 屎', ja: 'うんち' } },
    ],
  },
  {
    icon: '👍',
    emojis: [
      { char: '👍', keywords: { en: 'thumbs up like yes good', zh: '赞 点赞 好', ja: 'いいね 親指' } },
      { char: '👎', keywords: { en: 'thumbs down dislike no bad', zh: '踩 不行 差评', ja: 'だめ 親指下' } },
      { char: '👌', keywords: { en: 'ok perfect okay', zh: '好的 没问题', ja: 'オーケー 完璧' } },
      { char: '✌️', keywords: { en: 'peace victory', zh: '耶 胜利', ja: 'ピース 勝利' } },
      { char: '🤞', keywords: { en: 'fingers crossed luck hope', zh: '祈祷 好运', ja: '祈る 幸運' } },
      { char: '🤟', keywords: { en: 'love you gesture', zh: '爱你 手势', ja: 'アイラブユー' } },
      { char: '🤙', keywords: { en: 'call me shaka', zh: '打电话 手势', ja: '電話して' } },
      { char: '👏', keywords: { en: 'clap applause bravo', zh: '鼓掌 棒', ja: '拍手 ブラボー' } },
      { char: '🙌', keywords: { en: 'raise hands praise hooray', zh: '举手 万岁 欢呼', ja: '万歳 やった' } },
      { char: '🙏', keywords: { en: 'pray thanks please', zh: '拜托 谢谢 祈祷', ja: 'お願い ありがとう 祈り' } },
      { char: '👋', keywords: { en: 'wave hello hi bye', zh: '挥手 你好 再见', ja: '手を振る こんにちは バイバイ' } },
      { char: '🤝', keywords: { en: 'handshake deal agree', zh: '握手 成交', ja: '握手 取引' } },
      { char: '💪', keywords: { en: 'muscle strong flex', zh: '肌肉 加油 力量', ja: '筋肉 頑張る' } },
      { char: '✍️', keywords: { en: 'writing hand', zh: '写字 书写', ja: '書く 執筆' } },
      { char: '👀', keywords: { en: 'eyes look watch', zh: '眼睛 看', ja: '目 見る' } },
    ],
  },
  {
    icon: '❤️',
    emojis: [
      { char: '❤️', keywords: { en: 'red heart love', zh: '红心 爱 喜欢', ja: '赤いハート 愛' } },
      { char: '🧡', keywords: { en: 'orange heart', zh: '橙心', ja: 'オレンジハート' } },
      { char: '💛', keywords: { en: 'yellow heart', zh: '黄心', ja: '黄色いハート' } },
      { char: '💚', keywords: { en: 'green heart', zh: '绿心', ja: '緑のハート' } },
      { char: '💙', keywords: { en: 'blue heart', zh: '蓝心', ja: '青いハート' } },
      { char: '💜', keywords: { en: 'purple heart', zh: '紫心', ja: '紫のハート' } },
      { char: '🖤', keywords: { en: 'black heart', zh: '黑心', ja: '黒いハート' } },
      { char: '🤍', keywords: { en: 'white heart', zh: '白心', ja: '白いハート' } },
      { char: '💔', keywords: { en: 'broken heart', zh: '心碎', ja: '失恋 ハート割れ' } },
      { char: '💕', keywords: { en: 'two hearts love', zh: '两颗心 喜欢', ja: 'ふたつのハート' } },
      { char: '💖', keywords: { en: 'sparkling heart', zh: '闪亮的心', ja: 'きらめくハート' } },
      { char: '💗', keywords: { en: 'growing heart', zh: '心动', ja: 'ときめき' } },
      { char: '💘', keywords: { en: 'heart arrow cupid', zh: '丘比特 一箭穿心', ja: '矢のハート キューピッド' } },
      { char: '💝', keywords: { en: 'heart gift ribbon', zh: '礼物 心', ja: 'リボンハート' } },
      { char: '✨', keywords: { en: 'sparkles shiny', zh: '闪亮 闪光', ja: 'キラキラ' } },
      { char: '⭐', keywords: { en: 'star', zh: '星星', ja: '星' } },
      { char: '🌟', keywords: { en: 'glowing star', zh: '闪耀星星', ja: '輝く星' } },
      { char: '🔥', keywords: { en: 'fire lit hot flame', zh: '火 火焰 厉害', ja: '炎 火' } },
      { char: '💯', keywords: { en: 'hundred perfect score', zh: '满分 一百', ja: '百点 満点' } },
      { char: '💥', keywords: { en: 'boom explosion collision', zh: '爆炸', ja: '爆発 ドカン' } },
      { char: '⚡', keywords: { en: 'lightning bolt zap', zh: '闪电', ja: '稲妻 雷' } },
      { char: '🎉', keywords: { en: 'party tada celebrate', zh: '庆祝 撒花', ja: 'お祝い クラッカー' } },
      { char: '🎊', keywords: { en: 'confetti ball celebrate', zh: '彩球 庆祝', ja: 'くす玉 祝い' } },
      { char: '🎈', keywords: { en: 'balloon', zh: '气球', ja: '風船' } },
    ],
  },
  {
    icon: '🐱',
    emojis: [
      { char: '🐶', keywords: { en: 'dog puppy', zh: '狗 小狗', ja: '犬 いぬ' } },
      { char: '🐱', keywords: { en: 'cat kitten', zh: '猫 小猫', ja: '猫 ねこ' } },
      { char: '🐭', keywords: { en: 'mouse', zh: '老鼠', ja: 'ねずみ' } },
      { char: '🐹', keywords: { en: 'hamster', zh: '仓鼠', ja: 'ハムスター' } },
      { char: '🐰', keywords: { en: 'rabbit bunny', zh: '兔子', ja: 'うさぎ' } },
      { char: '🦊', keywords: { en: 'fox', zh: '狐狸', ja: 'きつね' } },
      { char: '🐻', keywords: { en: 'bear', zh: '熊', ja: 'くま' } },
      { char: '🐼', keywords: { en: 'panda', zh: '熊猫', ja: 'パンダ' } },
      { char: '🐨', keywords: { en: 'koala', zh: '考拉 树袋熊', ja: 'コアラ' } },
      { char: '🐯', keywords: { en: 'tiger', zh: '老虎', ja: 'とら' } },
      { char: '🦁', keywords: { en: 'lion', zh: '狮子', ja: 'ライオン' } },
      { char: '🐮', keywords: { en: 'cow', zh: '牛', ja: 'うし' } },
      { char: '🐷', keywords: { en: 'pig', zh: '猪', ja: 'ぶた' } },
      { char: '🐸', keywords: { en: 'frog', zh: '青蛙', ja: 'かえる' } },
      { char: '🐵', keywords: { en: 'monkey', zh: '猴子', ja: 'さる' } },
      { char: '🐔', keywords: { en: 'chicken', zh: '鸡', ja: 'にわとり' } },
      { char: '🐧', keywords: { en: 'penguin', zh: '企鹅', ja: 'ペンギン' } },
      { char: '🐦', keywords: { en: 'bird', zh: '鸟', ja: '鳥' } },
      { char: '🦄', keywords: { en: 'unicorn', zh: '独角兽', ja: 'ユニコーン' } },
      { char: '🐝', keywords: { en: 'bee honey', zh: '蜜蜂', ja: 'みつばち' } },
      { char: '🦋', keywords: { en: 'butterfly', zh: '蝴蝶', ja: 'ちょうちょ' } },
      { char: '🌸', keywords: { en: 'blossom flower cherry', zh: '樱花 花', ja: '桜 花' } },
      { char: '🌹', keywords: { en: 'rose flower', zh: '玫瑰 花', ja: 'バラ' } },
      { char: '🌻', keywords: { en: 'sunflower', zh: '向日葵', ja: 'ひまわり' } },
      { char: '🌵', keywords: { en: 'cactus', zh: '仙人掌', ja: 'サボテン' } },
      { char: '🍀', keywords: { en: 'clover luck', zh: '四叶草 幸运', ja: 'クローバー 幸運' } },
    ],
  },
  {
    icon: '🍔',
    emojis: [
      { char: '🍎', keywords: { en: 'apple fruit', zh: '苹果 水果', ja: 'りんご' } },
      { char: '🍌', keywords: { en: 'banana fruit', zh: '香蕉', ja: 'バナナ' } },
      { char: '🍓', keywords: { en: 'strawberry', zh: '草莓', ja: 'いちご' } },
      { char: '🍇', keywords: { en: 'grapes', zh: '葡萄', ja: 'ぶどう' } },
      { char: '🍑', keywords: { en: 'peach', zh: '桃子', ja: 'もも' } },
      { char: '🍉', keywords: { en: 'watermelon', zh: '西瓜', ja: 'すいか' } },
      { char: '🍒', keywords: { en: 'cherry cherries', zh: '樱桃', ja: 'さくらんぼ' } },
      { char: '🥑', keywords: { en: 'avocado', zh: '牛油果', ja: 'アボカド' } },
      { char: '🍔', keywords: { en: 'burger hamburger', zh: '汉堡', ja: 'ハンバーガー' } },
      { char: '🍟', keywords: { en: 'fries chips', zh: '薯条', ja: 'ポテト フライ' } },
      { char: '🍕', keywords: { en: 'pizza', zh: '披萨', ja: 'ピザ' } },
      { char: '🌭', keywords: { en: 'hotdog', zh: '热狗', ja: 'ホットドッグ' } },
      { char: '🍿', keywords: { en: 'popcorn', zh: '爆米花', ja: 'ポップコーン' } },
      { char: '🍩', keywords: { en: 'donut doughnut', zh: '甜甜圈', ja: 'ドーナツ' } },
      { char: '🍪', keywords: { en: 'cookie', zh: '饼干 曲奇', ja: 'クッキー' } },
      { char: '🎂', keywords: { en: 'cake birthday', zh: '蛋糕 生日', ja: 'ケーキ 誕生日' } },
      { char: '🍰', keywords: { en: 'cake slice shortcake', zh: '蛋糕', ja: 'ショートケーキ' } },
      { char: '🍫', keywords: { en: 'chocolate', zh: '巧克力', ja: 'チョコ' } },
      { char: '🍬', keywords: { en: 'candy sweet', zh: '糖果', ja: 'キャンディ あめ' } },
      { char: '🍦', keywords: { en: 'icecream soft serve', zh: '冰淇淋', ja: 'ソフトクリーム アイス' } },
      { char: '☕', keywords: { en: 'coffee tea hot', zh: '咖啡', ja: 'コーヒー' } },
      { char: '🍵', keywords: { en: 'tea matcha green', zh: '茶 抹茶', ja: 'お茶 抹茶' } },
      { char: '🍺', keywords: { en: 'beer', zh: '啤酒', ja: 'ビール' } },
      { char: '🍷', keywords: { en: 'wine', zh: '红酒 葡萄酒', ja: 'ワイン' } },
      { char: '🥂', keywords: { en: 'cheers toast champagne', zh: '干杯 庆祝', ja: '乾杯 シャンパン' } },
    ],
  },
  {
    icon: '⚽',
    emojis: [
      { char: '⚽', keywords: { en: 'soccer football', zh: '足球', ja: 'サッカー' } },
      { char: '🏀', keywords: { en: 'basketball', zh: '篮球', ja: 'バスケ' } },
      { char: '🎮', keywords: { en: 'game controller gaming', zh: '游戏 手柄', ja: 'ゲーム コントローラー' } },
      { char: '🎲', keywords: { en: 'dice game', zh: '骰子', ja: 'サイコロ' } },
      { char: '🎸', keywords: { en: 'guitar music', zh: '吉他', ja: 'ギター' } },
      { char: '🎹', keywords: { en: 'piano keyboard music', zh: '钢琴', ja: 'ピアノ' } },
      { char: '🎤', keywords: { en: 'mic sing karaoke', zh: '麦克风 唱歌', ja: 'マイク カラオケ' } },
      { char: '🎧', keywords: { en: 'headphones music', zh: '耳机', ja: 'ヘッドホン 音楽' } },
      { char: '🎬', keywords: { en: 'movie clapper film', zh: '电影', ja: '映画 クラッパー' } },
      { char: '🎨', keywords: { en: 'art paint palette', zh: '艺术 画画', ja: 'アート 絵' } },
      { char: '📷', keywords: { en: 'camera photo', zh: '相机 拍照', ja: 'カメラ 写真' } },
      { char: '🎁', keywords: { en: 'gift present', zh: '礼物', ja: 'プレゼント 贈り物' } },
      { char: '🏆', keywords: { en: 'trophy win champion', zh: '奖杯 冠军', ja: 'トロフィー 優勝' } },
      { char: '🥇', keywords: { en: 'gold medal first', zh: '金牌 第一', ja: '金メダル' } },
      { char: '🎓', keywords: { en: 'graduation cap study', zh: '毕业 学习', ja: '卒業 学業' } },
      { char: '💡', keywords: { en: 'idea lightbulb', zh: '灵感 点子 灯泡', ja: 'アイデア 電球' } },
      { char: '📚', keywords: { en: 'books study read', zh: '书 学习 阅读', ja: '本 勉強' } },
      { char: '✏️', keywords: { en: 'pencil write', zh: '铅笔 写', ja: '鉛筆 書く' } },
      { char: '💻', keywords: { en: 'laptop computer code', zh: '电脑 笔记本 编程', ja: 'パソコン コード' } },
      { char: '📱', keywords: { en: 'phone mobile', zh: '手机', ja: 'スマホ 携帯' } },
      { char: '⌚', keywords: { en: 'watch time', zh: '手表 时间', ja: '時計 時間' } },
      { char: '🔔', keywords: { en: 'bell notification', zh: '铃铛 通知', ja: 'ベル 通知' } },
      { char: '✅', keywords: { en: 'check done yes tick', zh: '对勾 完成', ja: 'チェック 完了' } },
      { char: '❌', keywords: { en: 'cross no wrong x', zh: '叉 错误', ja: 'バツ 間違い' } },
      { char: '❓', keywords: { en: 'question mark', zh: '问号', ja: '疑問符 はてな' } },
      { char: '❗', keywords: { en: 'exclamation mark', zh: '感叹号', ja: '感嘆符' } },
      { char: '💤', keywords: { en: 'sleep zzz', zh: '睡觉', ja: '睡眠 zzz' } },
      { char: '🌙', keywords: { en: 'moon night', zh: '月亮 晚上', ja: '月 夜' } },
      { char: '☀️', keywords: { en: 'sun sunny', zh: '太阳 晴天', ja: '太陽 晴れ' } },
      { char: '🌈', keywords: { en: 'rainbow', zh: '彩虹', ja: '虹' } },
    ],
  },
]
