/**
 * tarot.ts — Tarot feature configuration (single source of truth).
 *
 * ─────────────────────────────────────────────────────────────────────
 *  ASSET-SWAP INTERFACE (Task 3)
 * ─────────────────────────────────────────────────────────────────────
 * Every image URL and audio file path the tarot module touches is defined
 * HERE and nowhere else. When official art / audio arrive, edit only the
 * `TAROT_ASSETS` block below (and optionally each card's `image`); no
 * component logic needs to change.
 *
 * Placeholder strategy while assets are missing:
 *   - Images: an empty string ('') means "no art yet" → the component
 *     renders a code-generated CSS gradient derived from each card's `hue`.
 *     To use a real/remote image instead, set the path (e.g.
 *     `/assets/tarot/00_fool.webp` or a https URL).
 *   - Audio: empty paths mean "no audio yet" → useTarotSound falls back to
 *     a synthesized Web Audio beep + console.log. Set a real path to play
 *     an actual file.
 */

// ── Asset paths (edit these when real assets land) ──────────────────────

export const TAROT_ASSETS = {
  /**
   * Card-back artwork. '' → CSS gradient placeholder.
   * Placeholder SVG generated by scripts/gen-tarot-cards.mjs.
   */
  cardBackImage: '/assets/tarot/card-back.svg',

  /**
   * Builder for a card's front artwork from its id. Return '' to fall back to
   * the per-card gradient. Currently points at the generated placeholder SVGs;
   * swap to real art later, e.g. `/assets/tarot/${pad}.webp`.
   */
  cardFrontImage: (id: number): string =>
    `/assets/tarot/${String(id).padStart(2, '0')}.svg`,

  /** Sound effect file paths. '' → synthesized Web Audio placeholder. */
  audio: {
    draw: '',
    flip: '',
  },
} as const

// ── Timing knobs ────────────────────────────────────────────────────────

export const TAROT_TIMINGS = {
  /** 3D flip duration (ms). Must match the CSS transition in TarotCard.vue. */
  flipMs: 700,
  /** Lower / upper bound of the simulated "interpreting" delay (ms). */
  loadingMinMs: 1000,
  loadingMaxMs: 2000,
} as const

/**
 * Main-window size (logical px) while the tarot overlay is open, per character
 * size tier. The reading needs more room than the pet sprite, and the size
 * scales with the 大中小 (small / medium / large) setting so it stays
 * proportional to the character. On close the window restores to CHAR_SIZE_DIMS.
 */
export const TAROT_WINDOW_DIMS: Record<'small' | 'medium' | 'large', [number, number]> = {
  small:  [300, 470],
  medium: [340, 530],
  large:  [380, 590],
}

// ── Card data model ─────────────────────────────────────────────────────

export interface TarotCard {
  /** 0–21, the Major Arcana index. */
  id: number
  card_name: string
  /**
   * Placeholder/real front image URL. '' → render a CSS gradient using `hue`.
   * Kept per-card so individual cards can be swapped independently of the
   * global `TAROT_ASSETS.cardFrontImage` builder.
   */
  image_placeholder: string
  /** Base hue (0–360) for the generated gradient when no image is set. */
  hue: number
  /** Upright interpretation. */
  fortune_text: string
  /** Reversed interpretation — shown when the card is drawn inverted. */
  reversed_text: string
}

// ── The 22 Major Arcana (static config — no API, no network) ────────────

export const MAJOR_ARCANA: readonly TarotCard[] = [
  { id: 0,  card_name: 'The Fool',           image_placeholder: '', hue: 48,
    fortune_text:  'A fresh beginning calls. Step off the cliff with an open heart — today rewards the curious and the brave.',
    reversed_text: 'Recklessness is mistaken for freedom. Pause before the leap — an unexamined risk may not be worth taking.' },
  { id: 1,  card_name: 'The Magician',       image_placeholder: '', hue: 12,
    fortune_text:  'You hold every tool you need. Focus your will and what felt scattered will snap into a single, clear intention.',
    reversed_text: 'Your tools are there but remain unused. Manipulation or self-doubt is blocking the work — realign your intent.' },
  { id: 2,  card_name: 'The High Priestess', image_placeholder: '', hue: 250,
    fortune_text:  'Trust the quiet voice beneath the noise. The answer you seek is already known to you — listen inward.',
    reversed_text: 'Secrets withheld or intuition suppressed are causing confusion. Surface what is hidden before moving forward.' },
  { id: 3,  card_name: 'The Empress',        image_placeholder: '', hue: 330,
    fortune_text:  'Abundance is ripening around you. Nurture an idea, a bond, or yourself, and watch it bloom in kind.',
    reversed_text: 'Neglect or overindulgence is choking growth. Return to the basics of self-care before you can nurture others.' },
  { id: 4,  card_name: 'The Emperor',        image_placeholder: '', hue: 0,
    fortune_text:  'Structure brings freedom. Set a firm boundary or a steady plan today and the chaos will fall into line.',
    reversed_text: 'Rigid control is becoming its own trap. Loosen your grip — inflexibility now leads to avoidable collapse.' },
  { id: 5,  card_name: 'The Hierophant',     image_placeholder: '', hue: 36,
    fortune_text:  'Wisdom from tradition or a mentor lights the path. Honor what has been proven before improvising anew.',
    reversed_text: 'Dogma or outdated rules are holding you back. Challenge convention thoughtfully and chart your own course.' },
  { id: 6,  card_name: 'The Lovers',         image_placeholder: '', hue: 345,
    fortune_text:  'A choice of the heart draws near. Align your actions with your values and the right connection deepens.',
    reversed_text: 'A relationship or decision is misaligned with your true values. Avoidance only deepens the disharmony.' },
  { id: 7,  card_name: 'The Chariot',        image_placeholder: '', hue: 210,
    fortune_text:  'Victory favors momentum. Grip the reins of opposing forces and drive straight toward your goal.',
    reversed_text: 'Opposing drives are pulling you in contradictory directions. Regain focus before force becomes aggression.' },
  { id: 8,  card_name: 'Strength',           image_placeholder: '', hue: 30,
    fortune_text:  "Gentle courage outlasts brute force. Meet today's challenge with patience and a calm, steady hand.",
    reversed_text: 'Self-doubt or suppressed fears are sapping your courage. Acknowledge weakness — that is the first act of strength.' },
  { id: 9,  card_name: 'The Hermit',         image_placeholder: '', hue: 200,
    fortune_text:  'Step back from the crowd. A little solitude will turn your inner lamp up bright enough to see the next step.',
    reversed_text: 'Isolation has turned into withdrawal. The lamp still glows — take a small step back toward the world.' },
  { id: 10, card_name: 'Wheel of Fortune',   image_placeholder: '', hue: 280,
    fortune_text:  'The wheel turns in your favor. A shift in luck arrives — ride the upswing and stay flexible as it spins.',
    reversed_text: 'An unwelcome turn has arrived. Resist the urge to force the wheel; this phase will pass if you adapt.' },
  { id: 11, card_name: 'Justice',            image_placeholder: '', hue: 190,
    fortune_text:  'Balance is restored through honesty. Speak plainly and act fairly; what you put out returns in equal measure.',
    reversed_text: 'A dishonest act or unfair outcome clouds your path. Own your part in the imbalance before it compounds.' },
  { id: 12, card_name: 'The Hanged Man',     image_placeholder: '', hue: 170,
    fortune_text:  'Pause and shift your view. Surrendering control for a moment reveals the answer that striving could not.',
    reversed_text: 'Indecision is no longer a pause — it is stagnation. The sacrifice needed to move forward must be made.' },
  { id: 13, card_name: 'Death',              image_placeholder: '', hue: 270,
    fortune_text:  'An ending clears the way. Release what has run its course and a powerful transformation can finally begin.',
    reversed_text: 'Resistance to change keeps an old form alive past its time. What needs to end is simply waiting for your permission.' },
  { id: 14, card_name: 'Temperance',         image_placeholder: '', hue: 160,
    fortune_text:  'Blend extremes into harmony. Moderation and patience today brew exactly the calm you have been craving.',
    reversed_text: 'Imbalance is spilling into excess or impatience. Step back from the extremes before they erode what you value.' },
  { id: 15, card_name: 'The Devil',          image_placeholder: '', hue: 350,
    fortune_text:  'Notice the chains you chose. A habit or attachment binds you only as tightly as you permit — you can step free.',
    reversed_text: 'A shadow pattern is loosening its grip. The desire to break free is real — trust that impulse and act on it.' },
  { id: 16, card_name: 'The Tower',          image_placeholder: '', hue: 8,
    fortune_text:  'A sudden jolt shakes loose what was unstable. It feels abrupt, but this clearing makes room for truer ground.',
    reversed_text: 'Inevitable disruption is being postponed through fear. The collapse that is coming will be gentler if you stop clinging.' },
  { id: 17, card_name: 'The Star',           image_placeholder: '', hue: 195,
    fortune_text:  'Hope returns, soft and bright. After the storm, healing flows freely — make a wish and trust the calm ahead.',
    reversed_text: 'Hopelessness or despair is dimming the light. The star has not gone out — rest, and it will come back into view.' },
  { id: 18, card_name: 'The Moon',           image_placeholder: '', hue: 235,
    fortune_text:  'Not all is as it seems tonight. Move slowly through the fog; let intuition, not fear, guide your footing.',
    reversed_text: 'Confusion is beginning to lift. Trust the facts that are emerging and release the fears that kept truth hidden.' },
  { id: 19, card_name: 'The Sun',            image_placeholder: '', hue: 45,
    fortune_text:  'Pure joy and clarity shine down. Success and warmth are within reach — let yourself fully enjoy the light.',
    reversed_text: 'Optimism is slightly out of focus — perhaps forced or blocked. Quiet the noise and let genuine joy find its way through.' },
  { id: 20, card_name: 'Judgement',          image_placeholder: '', hue: 215,
    fortune_text:  'A call to rise renews you. Reflect, forgive, and answer honestly; a fresh chapter awaits your yes.',
    reversed_text: 'Self-judgment or guilt is silencing the call. Forgive yourself first — the renewal cannot begin until you do.' },
  { id: 21, card_name: 'The World',          image_placeholder: '', hue: 140,
    fortune_text:  'A cycle completes in triumph. You have come full circle — celebrate the achievement, then step into the next.',
    reversed_text: 'A cycle lingers unfinished. There is one loose end left to tie before you can truly begin the next chapter.' },
]
