/**
 * tarot.ts — Tarot feature configuration (single source of truth).
 *
 * ─────────────────────────────────────────────────────────────────────
 *  ASSET-SWAP INTERFACE
 * ─────────────────────────────────────────────────────────────────────
 * Every image URL and audio file path the tarot module touches is defined
 * HERE and nowhere else. When official art / audio arrive, edit only the
 * `TAROT_ASSETS` block below; no component logic needs to change.
 *
 *   - Images: cardFrontImage(id) → `/assets/tarot/NN.svg` (NN = zero-padded id
 *     0–77). Placeholder SVGs are generated by scripts/gen-tarot-cards.mjs.
 *     Drop real files with the same names to replace them; delete them to fall
 *     back to the generated placeholders.
 *   - Audio: empty paths mean "no audio yet" → useTarotSound falls back to a
 *     synthesized Web Audio cue. Set a real path to play an actual file.
 *
 *  I18N: every player-facing string (card names + interpretations) is a
 *  LocalizedText { en, zh, ja }. The component renders the field for the
 *  active locale via useI18n(). UI chrome strings live in the i18n bundles
 *  (src/i18n/locales/*) under the `tarot` key.
 */

// ── Deck art selection ──────────────────────────────────────────────────
//
// Two interchangeable decks live in public/assets/tarot/:
//   - classic — the Rider-Waite JPG deck the user supplied (descriptive
//     filenames, see CLASSIC_DECK_FILES below).
//   - placeholder — the generated SVG set (scripts/gen-tarot-cards.mjs),
//     named NN.svg by id. Delete/keep independently of the classic deck.
//
// Flip this single flag to switch between them; nothing else needs to change.
const USE_CLASSIC_DECK = true

/**
 * Classic-deck front filenames, indexed by card id (0–77). Major Arcana use
 * `NN-Name.jpg`; Minor Arcana use `Suit` + zero-padded rank (01=Ace … 14=King),
 * which matches the deck order (Wands 22–35, Cups 36–49, Swords 50–63,
 * Pentacles 64–77).
 */
const CLASSIC_DECK_FILES: readonly string[] = [
  '00-TheFool.jpg', '01-TheMagician.jpg', '02-TheHighPriestess.jpg', '03-TheEmpress.jpg',
  '04-TheEmperor.jpg', '05-TheHierophant.jpg', '06-TheLovers.jpg', '07-TheChariot.jpg',
  '08-Strength.jpg', '09-TheHermit.jpg', '10-WheelOfFortune.jpg', '11-Justice.jpg',
  '12-TheHangedMan.jpg', '13-Death.jpg', '14-Temperance.jpg', '15-TheDevil.jpg',
  '16-TheTower.jpg', '17-TheStar.jpg', '18-TheMoon.jpg', '19-TheSun.jpg',
  '20-Judgement.jpg', '21-TheWorld.jpg',
  ...['Wands', 'Cups', 'Swords', 'Pentacles'].flatMap(suit =>
    Array.from({ length: 14 }, (_, r) => `${suit}${String(r + 1).padStart(2, '0')}.jpg`),
  ),
]

// ── Asset paths ─────────────────────────────────────────────────────────

export const TAROT_ASSETS = {
  /** Card-back artwork. '' → CSS gradient placeholder. */
  cardBackImage: USE_CLASSIC_DECK
    ? '/assets/tarot/CardBacks.jpg'
    : '/assets/tarot/card-back.svg',

  /**
   * Builder for a card's front artwork from its id (0–77). Returns the classic
   * JPG when USE_CLASSIC_DECK is true, otherwise the generated SVG placeholder.
   */
  cardFrontImage: (id: number): string =>
    USE_CLASSIC_DECK
      ? `/assets/tarot/${CLASSIC_DECK_FILES[id]}`
      : `/assets/tarot/${String(id).padStart(2, '0')}.svg`,

  /** Sound effect file paths. '' → synthesized Web Audio placeholder. */
  audio: {
    draw: '',
    flip: '',
  },
} as const

// ── Timing knobs ────────────────────────────────────────────────────────

export const TAROT_TIMINGS = {
  /** 3D flip duration (ms). Must match the CSS transition in TarotCard.vue. */
  flipMs: 700,
  /** Lower / upper bound of the simulated "interpreting" delay (ms). */
  loadingMinMs: 1000,
  loadingMaxMs: 2000,
} as const

/**
 * Main-window size (logical px) while the tarot overlay is open, per character
 * size tier. The reading needs more room than the pet sprite, and the size
 * scales with the 大中小 (small / medium / large) setting so it stays
 * proportional to the character. On close the window restores to CHAR_SIZE_DIMS.
 */
export const TAROT_WINDOW_DIMS: Record<'small' | 'medium' | 'large', [number, number]> = {
  small:  [300, 470],
  medium: [340, 530],
  large:  [380, 590],
}

// ── Card data model ─────────────────────────────────────────────────────

/** A player-facing string in every supported locale (keys match i18n Locale). */
export interface LocalizedText {
  en: string
  zh: string
  ja: string
}

export interface TarotCard {
  /** 0–77 (0–21 Major Arcana, 22–77 Minor Arcana: Wands, Cups, Swords, Pentacles). */
  id: number
  /** Localized card name. */
  card_name: LocalizedText
  /**
   * Per-card front image URL override. '' → use TAROT_ASSETS.cardFrontImage(id),
   * and if that file is missing the component falls back to a `hue` gradient.
   */
  image_placeholder: string
  /** Base hue (0–360) for the generated gradient + glow VFX. */
  hue: number
  /** Upright interpretation (localized). */
  fortune_text: LocalizedText
  /** Reversed interpretation (localized) — shown when drawn inverted. */
  reversed_text: LocalizedText
}

// ── The full 78-card deck (static config — no API, no network) ───────────

export const TAROT_DECK: readonly TarotCard[] = [
  // ── Major Arcana (0–21) ───────────────────────────────────────────────
  { id: 0, hue: 48, image_placeholder: '',
    card_name:     { en: 'The Fool', zh: '愚者', ja: '愚者' },
    fortune_text:  { en: 'A fresh beginning calls. Step off the cliff with an open heart — today rewards the curious and the brave.', zh: '崭新的旅程正在召唤。带着开放的心纵身一跃——今天属于好奇而勇敢的人。', ja: '新たな旅立ちの時。心を開いて一歩を踏み出そう——今日は好奇心と勇気を持つ者に微笑む。' },
    reversed_text: { en: 'Recklessness is mistaken for freedom. Pause before the leap — an unexamined risk may not be worth taking.', zh: '莽撞被误当成自由。纵身之前先停一停——未经思量的冒险未必值得。', ja: '無謀さを自由と取り違えている。飛び込む前に一呼吸を——軽率な賭けは割に合わない。' } },
  { id: 1, hue: 12, image_placeholder: '',
    card_name:     { en: 'The Magician', zh: '魔术师', ja: '魔術師' },
    fortune_text:  { en: 'You hold every tool you need. Focus your will and what felt scattered will snap into a single, clear intention.', zh: '你已握有所需的一切工具。集中意志，散乱之事自会凝聚成清晰的意图。', ja: '必要な道具はすべて手の中に。意志を集中すれば、散らばっていたものが一つの明確な目的へと結ばれる。' },
    reversed_text: { en: 'Your tools are there but remain unused. Manipulation or self-doubt is blocking the work — realign your intent.', zh: '工具就在手边却闲置未用。操弄或自我怀疑正阻碍着进展——重新校准你的意图。', ja: '道具はあるのに使われていない。ごまかしや自己不信が妨げになっている——意図を立て直そう。' } },
  { id: 2, hue: 250, image_placeholder: '',
    card_name:     { en: 'The High Priestess', zh: '女祭司', ja: '女教皇' },
    fortune_text:  { en: 'Trust the quiet voice beneath the noise. The answer you seek is already known to you — listen inward.', zh: '信任喧嚣之下那个安静的声音。你所寻的答案早已在心中——向内聆听。', ja: '喧騒の奥にある静かな声を信じて。求める答えはすでに自分の中にある——内なる声に耳を澄ませて。' },
    reversed_text: { en: 'Secrets withheld or intuition suppressed are causing confusion. Surface what is hidden before moving forward.', zh: '被隐瞒的秘密或被压抑的直觉带来了混乱。前行之前，先让潜藏之物浮现。', ja: '隠された秘密や抑え込んだ直感が混乱を招いている。進む前に、隠れたものを表に出そう。' } },
  { id: 3, hue: 330, image_placeholder: '',
    card_name:     { en: 'The Empress', zh: '女皇', ja: '女帝' },
    fortune_text:  { en: 'Abundance is ripening around you. Nurture an idea, a bond, or yourself, and watch it bloom in kind.', zh: '丰盛正在你周围成熟。悉心滋养一个想法、一段关系或你自己，看它如约绽放。', ja: '豊かさがあなたの周りで実りつつある。アイデアや絆、そして自分自身を育てれば、それは花開く。' },
    reversed_text: { en: 'Neglect or overindulgence is choking growth. Return to the basics of self-care before you can nurture others.', zh: '疏忽或过度放纵正扼杀着成长。先回到照顾自己的基本功，才能去滋养他人。', ja: '怠りや甘やかし過ぎが成長を妨げている。人を育てる前に、まず自分を労わる基本に戻ろう。' } },
  { id: 4, hue: 0, image_placeholder: '',
    card_name:     { en: 'The Emperor', zh: '皇帝', ja: '皇帝' },
    fortune_text:  { en: 'Structure brings freedom. Set a firm boundary or a steady plan today and the chaos will fall into line.', zh: '秩序带来自由。今天立下坚定的界限或稳妥的计划，混乱自会归位。', ja: '秩序が自由をもたらす。今日しっかりとした境界や計画を定めれば、混沌は整っていく。' },
    reversed_text: { en: 'Rigid control is becoming its own trap. Loosen your grip — inflexibility now leads to avoidable collapse.', zh: '僵硬的掌控正变成自缚的牢笼。松一松手——此刻的固执只会招致本可避免的崩塌。', ja: '硬直した支配がそれ自体の罠になっている。力を緩めて——今の頑なさは避けられたはずの崩壊を招く。' } },
  { id: 5, hue: 36, image_placeholder: '',
    card_name:     { en: 'The Hierophant', zh: '教皇', ja: '教皇' },
    fortune_text:  { en: 'Wisdom from tradition or a mentor lights the path. Honor what has been proven before improvising anew.', zh: '来自传统或导师的智慧照亮前路。在另辟蹊径之前，先尊重那些已被验证的东西。', ja: '伝統や師から得る知恵が道を照らす。新たに試みる前に、すでに実証されたものを敬おう。' },
    reversed_text: { en: 'Dogma or outdated rules are holding you back. Challenge convention thoughtfully and chart your own course.', zh: '教条或过时的规矩正拖住你。审慎地挑战成规，走出属于自己的路。', ja: '教条や時代遅れの規則があなたを縛っている。慣習を思慮深く問い直し、自分の道を描こう。' } },
  { id: 6, hue: 345, image_placeholder: '',
    card_name:     { en: 'The Lovers', zh: '恋人', ja: '恋人' },
    fortune_text:  { en: 'A choice of the heart draws near. Align your actions with your values and the right connection deepens.', zh: '一个发自内心的抉择即将到来。让行动与价值观一致，对的缘分便会加深。', ja: '心からの選択が近づいている。行動を価値観と重ねれば、正しい縁は深まっていく。' },
    reversed_text: { en: 'A relationship or decision is misaligned with your true values. Avoidance only deepens the disharmony.', zh: '一段关系或一个决定与你真正的价值观相悖。回避只会让失谐更深。', ja: 'ある関係や決断が、本当の価値観とずれている。避け続ければ不調和は深まるばかり。' } },
  { id: 7, hue: 210, image_placeholder: '',
    card_name:     { en: 'The Chariot', zh: '战车', ja: '戦車' },
    fortune_text:  { en: 'Victory favors momentum. Grip the reins of opposing forces and drive straight toward your goal.', zh: '胜利偏爱势头。握紧相反力量的缰绳，直直驶向你的目标。', ja: '勝利は勢いに味方する。相反する力の手綱を握り、まっすぐ目標へ進もう。' },
    reversed_text: { en: 'Opposing drives are pulling you in contradictory directions. Regain focus before force becomes aggression.', zh: '相互冲突的冲动正把你扯向矛盾的方向。在力量沦为蛮横之前，重拾专注。', ja: '相反する衝動が、あなたを矛盾した方向へ引っ張っている。力が暴走する前に集中を取り戻そう。' } },
  { id: 8, hue: 30, image_placeholder: '',
    card_name:     { en: 'Strength', zh: '力量', ja: '力' },
    fortune_text:  { en: "Gentle courage outlasts brute force. Meet today's challenge with patience and a calm, steady hand.", zh: '温柔的勇气比蛮力更持久。以耐心和沉稳的手，迎接今天的挑战。', ja: '穏やかな勇気は力任せに勝る。忍耐と落ち着いた手つきで、今日の試練に向き合おう。' },
    reversed_text: { en: 'Self-doubt or suppressed fears are sapping your courage. Acknowledge weakness — that is the first act of strength.', zh: '自我怀疑或被压抑的恐惧正消耗你的勇气。承认软弱——那正是力量的第一步。', ja: '自己不信や抑え込んだ恐れが勇気を削いでいる。弱さを認めること——それが強さの第一歩。' } },
  { id: 9, hue: 200, image_placeholder: '',
    card_name:     { en: 'The Hermit', zh: '隐士', ja: '隠者' },
    fortune_text:  { en: 'Step back from the crowd. A little solitude will turn your inner lamp up bright enough to see the next step.', zh: '暂时退离人群。一点独处，会把你内心的灯调亮，足以照见下一步。', ja: '人混みから一歩引いてみよう。少しの孤独が、次の一歩を照らすほどに内なる灯をともす。' },
    reversed_text: { en: 'Isolation has turned into withdrawal. The lamp still glows — take a small step back toward the world.', zh: '独处已变成了封闭。灯依然亮着——朝着世界，迈出一小步。', ja: '孤独が引きこもりに変わっている。灯はまだ灯っている——世界へ向けて小さな一歩を。' } },
  { id: 10, hue: 280, image_placeholder: '',
    card_name:     { en: 'Wheel of Fortune', zh: '命运之轮', ja: '運命の輪' },
    fortune_text:  { en: 'The wheel turns in your favor. A shift in luck arrives — ride the upswing and stay flexible as it spins.', zh: '轮盘正朝有利于你的方向转动。运势的转机已到——顺势而上，随它旋转保持灵活。', ja: '輪はあなたに有利に回る。運の転機が訪れる——上昇の波に乗り、回転に合わせて柔軟でいよう。' },
    reversed_text: { en: 'An unwelcome turn has arrived. Resist the urge to force the wheel; this phase will pass if you adapt.', zh: '一个不受欢迎的转折到来了。别强行去拨动轮盘；只要顺应，这一阶段终会过去。', ja: '望まぬ転機が訪れた。輪を無理に回そうとしないで——順応すれば、この時期は過ぎ去る。' } },
  { id: 11, hue: 190, image_placeholder: '',
    card_name:     { en: 'Justice', zh: '正义', ja: '正義' },
    fortune_text:  { en: 'Balance is restored through honesty. Speak plainly and act fairly; what you put out returns in equal measure.', zh: '平衡因诚实而重建。坦率直言、公正行事；你付出什么，便会等量地回到你身上。', ja: '正直さによって均衡が戻る。率直に語り、公正に振る舞おう——差し出したものは同じだけ返ってくる。' },
    reversed_text: { en: 'A dishonest act or unfair outcome clouds your path. Own your part in the imbalance before it compounds.', zh: '一桩不诚实之举或不公的结果遮蔽了前路。在失衡加剧之前，先认下你自己的那一份。', ja: '不誠実な行いや不公平な結果が道を曇らせている。不均衡が増す前に、自分の責任を認めよう。' } },
  { id: 12, hue: 170, image_placeholder: '',
    card_name:     { en: 'The Hanged Man', zh: '倒吊人', ja: '吊られた男' },
    fortune_text:  { en: 'Pause and shift your view. Surrendering control for a moment reveals the answer that striving could not.', zh: '停下来，换个角度。短暂地放下掌控，会显露出努力争取所求不到的答案。', ja: '立ち止まり、視点を変えてみよう。一度コントロールを手放すと、あがいても見えなかった答えが現れる。' },
    reversed_text: { en: 'Indecision is no longer a pause — it is stagnation. The sacrifice needed to move forward must be made.', zh: '犹豫不决已不再是暂停，而是停滞。要向前，就必须做出该有的牺牲。', ja: '優柔不断はもはや休止ではなく停滞だ。前へ進むために必要な犠牲を払う時。' } },
  { id: 13, hue: 270, image_placeholder: '',
    card_name:     { en: 'Death', zh: '死神', ja: '死神' },
    fortune_text:  { en: 'An ending clears the way. Release what has run its course and a powerful transformation can finally begin.', zh: '一个结束为新生让路。放下已走到尽头的事物，一场深刻的蜕变才能真正开始。', ja: '終わりが道を切り開く。役目を終えたものを手放せば、力強い変容がようやく始まる。' },
    reversed_text: { en: 'Resistance to change keeps an old form alive past its time. What needs to end is simply waiting for your permission.', zh: '对改变的抗拒，让一个旧形态苟延残喘。该结束的，只是在等你点头。', ja: '変化への抵抗が、古い形を寿命以上に長らえさせている。終わるべきものは、あなたの許しを待っているだけ。' } },
  { id: 14, hue: 160, image_placeholder: '',
    card_name:     { en: 'Temperance', zh: '节制', ja: '節制' },
    fortune_text:  { en: 'Blend extremes into harmony. Moderation and patience today brew exactly the calm you have been craving.', zh: '把两极调和成和谐。今日的适度与耐心，正酿出你一直渴望的平静。', ja: '両極を調和へと溶け合わせよう。今日の節度と忍耐が、求めていた静けさを醸し出す。' },
    reversed_text: { en: 'Imbalance is spilling into excess or impatience. Step back from the extremes before they erode what you value.', zh: '失衡正溢成过度或焦躁。在两极侵蚀你所珍视之物前，退后一步。', ja: 'バランスの崩れが、過剰や焦りとなって溢れている。大切なものが損なわれる前に、極端から距離を。' } },
  { id: 15, hue: 350, image_placeholder: '',
    card_name:     { en: 'The Devil', zh: '恶魔', ja: '悪魔' },
    fortune_text:  { en: 'Notice the chains you chose. A habit or attachment binds you only as tightly as you permit — you can step free.', zh: '看清那些你自己选上的锁链。一个习惯或执念，束缚你的力度只取决于你的允许——你能挣脱。', ja: '自ら選んだ鎖に気づこう。習慣や執着があなたを縛る強さは、許した分だけ——あなたは抜け出せる。' },
    reversed_text: { en: 'A shadow pattern is loosening its grip. The desire to break free is real — trust that impulse and act on it.', zh: '一种阴影模式正松开掌控。想要挣脱的渴望是真实的——信任那股冲动，并去行动。', ja: '影の習性が締めつけを緩めている。自由になりたい願いは本物だ——その衝動を信じて動こう。' } },
  { id: 16, hue: 8, image_placeholder: '',
    card_name:     { en: 'The Tower', zh: '高塔', ja: '塔' },
    fortune_text:  { en: 'A sudden jolt shakes loose what was unstable. It feels abrupt, but this clearing makes room for truer ground.', zh: '一记突如其来的震动，抖落了原本就不稳的东西。它来得猝然，却清出空间，让更真实的根基得以立足。', ja: '突然の衝撃が、不安定だったものを崩し落とす。唐突に思えても、この一掃がより確かな土台の場所を作る。' },
    reversed_text: { en: 'Inevitable disruption is being postponed through fear. The collapse that is coming will be gentler if you stop clinging.', zh: '因恐惧，一场不可避免的崩解被一再推迟。若你不再死守，将临的坍塌会温和许多。', ja: '避けられない崩壊が、恐れによって先延ばしされている。しがみつくのをやめれば、来るべき崩れは穏やかになる。' } },
  { id: 17, hue: 195, image_placeholder: '',
    card_name:     { en: 'The Star', zh: '星星', ja: '星' },
    fortune_text:  { en: 'Hope returns, soft and bright. After the storm, healing flows freely — make a wish and trust the calm ahead.', zh: '希望归来，柔和而明亮。风暴过后，疗愈自在流淌——许个愿，信任前方的平静。', ja: '希望が、やわらかく明るく戻ってくる。嵐の後、癒やしは自由に流れる——願いを込めて、これからの静けさを信じて。' },
    reversed_text: { en: 'Hopelessness or despair is dimming the light. The star has not gone out — rest, and it will come back into view.', zh: '绝望或灰心正让星光黯淡。星并未熄灭——好好休息，它会重新映入眼帘。', ja: '絶望や落胆が光を曇らせている。星は消えていない——休めば、また見えてくる。' } },
  { id: 18, hue: 235, image_placeholder: '',
    card_name:     { en: 'The Moon', zh: '月亮', ja: '月' },
    fortune_text:  { en: 'Not all is as it seems tonight. Move slowly through the fog; let intuition, not fear, guide your footing.', zh: '今夜，并非一切都如表象。在雾中缓步而行；让直觉而非恐惧，指引你的脚步。', ja: '今宵、見たままがすべてではない。霧の中をゆっくり進もう——恐れではなく直感に足元を委ねて。' },
    reversed_text: { en: 'Confusion is beginning to lift. Trust the facts that are emerging and release the fears that kept truth hidden.', zh: '困惑开始消散。信任正浮现的事实，放下那些曾让真相藏匿的恐惧。', ja: '混乱が晴れ始めている。現れてくる事実を信じ、真実を覆い隠していた恐れを手放そう。' } },
  { id: 19, hue: 45, image_placeholder: '',
    card_name:     { en: 'The Sun', zh: '太阳', ja: '太陽' },
    fortune_text:  { en: 'Pure joy and clarity shine down. Success and warmth are within reach — let yourself fully enjoy the light.', zh: '纯粹的喜悦与清明洒落而下。成功与温暖触手可及——尽情享受这片光吧。', ja: '純粋な喜びと明晰さが降り注ぐ。成功と温もりはすぐそこに——その光を心ゆくまで楽しもう。' },
    reversed_text: { en: 'Optimism is slightly out of focus — perhaps forced or blocked. Quiet the noise and let genuine joy find its way through.', zh: '乐观稍稍失焦——也许是勉强，也许被阻。让喧嚣安静下来，让真正的喜悦自己找到出路。', ja: '楽観が少しぼやけている——無理をしているか、塞がれているのかも。雑音を静め、本当の喜びが差し込む道を空けて。' } },
  { id: 20, hue: 215, image_placeholder: '',
    card_name:     { en: 'Judgement', zh: '审判', ja: '審判' },
    fortune_text:  { en: 'A call to rise renews you. Reflect, forgive, and answer honestly; a fresh chapter awaits your yes.', zh: '一声唤你起身的召唤令你焕新。反思、宽恕、诚实作答；崭新的篇章正等你点头。', ja: '立ち上がれという呼び声があなたを新たにする。省み、赦し、正直に応えよう——新しい章があなたの「はい」を待っている。' },
    reversed_text: { en: 'Self-judgment or guilt is silencing the call. Forgive yourself first — the renewal cannot begin until you do.', zh: '自我审判或愧疚正让那召唤沉默。先原谅你自己——否则更新无法开始。', ja: '自己批判や罪悪感が、その呼び声を黙らせている。まず自分を赦そう——そうしない限り再生は始まらない。' } },
  { id: 21, hue: 140, image_placeholder: '',
    card_name:     { en: 'The World', zh: '世界', ja: '世界' },
    fortune_text:  { en: 'A cycle completes in triumph. You have come full circle — celebrate the achievement, then step into the next.', zh: '一个循环在凯旋中圆满。你已走完整整一圈——为这成就庆祝，再迈入下一段。', ja: '一つの周期が勝利のうちに完結する。あなたは一巡りを終えた——その達成を祝い、次へと踏み出そう。' },
    reversed_text: { en: 'A cycle lingers unfinished. There is one loose end left to tie before you can truly begin the next chapter.', zh: '一个循环尚未收尾。还有一处未了之事待你系紧，才能真正开启下一章。', ja: '周期がやり残しのまま留まっている。次の章を本当に始める前に、結ぶべき一つの結び目が残っている。' } },

  // ── Wands (22–35) ─────────────────────────────────────────────────────
  { id: 22, hue: 18, image_placeholder: '',
    card_name:     { en: 'Ace of Wands', zh: '权杖一', ja: 'ワンドのエース' },
    fortune_text:  { en: 'A spark of inspiration ignites. Seize this burst of creative energy and begin before the fire cools.', zh: '一束灵感的火花被点燃。抓住这股迸发的创造能量，趁火未冷便开始。', ja: '霊感の火花が灯る。湧き上がる創造のエネルギーをつかみ、火が冷める前に始めよう。' },
    reversed_text: { en: 'The spark sputters. Delays or hesitation are smothering a new idea — clear the kindling and try again.', zh: '火花忽明忽灭。拖延或犹豫正闷熄一个新点子——清理引火物，再试一次。', ja: '火花がくすぶる。遅れや迷いが新しい着想を覆い消している——焚きつけを整え、もう一度。' } },
  { id: 23, hue: 22, image_placeholder: '',
    card_name:     { en: 'Two of Wands', zh: '权杖二', ja: 'ワンドの2' },
    fortune_text:  { en: 'The world is in your hands; now choose a direction. Plan boldly — this is the moment to map your next venture.', zh: '世界握在你手中；现在，选定一个方向。大胆规划——此刻正是为下一次冒险绘图的时机。', ja: '世界はあなたの手の中——今こそ方向を選ぶ時。大胆に計画を立て、次の冒険の地図を描こう。' },
    reversed_text: { en: 'Fear of the unknown keeps you planning but never leaving. A safe choice now may cost you the bigger horizon.', zh: '对未知的恐惧让你只筹划却从不启程。此刻求稳的选择，或会让你失去更辽阔的天地。', ja: '未知への恐れが、計画ばかりで出発させない。今の安全な選択は、より大きな地平を犠牲にするかも。' } },
  { id: 24, hue: 26, image_placeholder: '',
    card_name:     { en: 'Three of Wands', zh: '权杖三', ja: 'ワンドの3' },
    fortune_text:  { en: 'Your early efforts set sail. Expansion is underway — watch the horizon for the opportunities you set in motion.', zh: '你早先的努力已经扬帆。扩展正在进行——望向地平线，迎接你亲手启动的机遇。', ja: '早くからの努力が帆を上げた。広がりは進行中——自ら動かした好機を、地平線に探そう。' },
    reversed_text: { en: 'Plans stall or arrive late. Reassess the foundations before pushing further outward.', zh: '计划停滞或姗姗来迟。在向外推进之前，重新审视根基。', ja: '計画が滞るか、遅れて届く。さらに外へ広げる前に、土台を見直そう。' } },
  { id: 25, hue: 30, image_placeholder: '',
    card_name:     { en: 'Four of Wands', zh: '权杖四', ja: 'ワンドの4' },
    fortune_text:  { en: 'Celebration and stable ground. A milestone is worth honoring — gather with those who share your joy.', zh: '庆祝，与稳固的根基。一座里程碑值得致敬——与分享你喜悦的人相聚吧。', ja: '祝祭と安定した足場。節目は称えるに値する——喜びを分かち合える人と集おう。' },
    reversed_text: { en: 'Harmony feels unfinished. A delayed homecoming or shaky foundation asks for attention before you celebrate.', zh: '和谐似乎尚未完整。一次延宕的归家或不稳的根基，在庆祝之前需要你留意。', ja: '調和がどこか未完成に感じる。遅れた帰郷や不安定な土台が、祝う前に気づきを求めている。' } },
  { id: 26, hue: 34, image_placeholder: '',
    card_name:     { en: 'Five of Wands', zh: '权杖五', ja: 'ワンドの5' },
    fortune_text:  { en: 'Friction sparks growth. Healthy competition or lively debate sharpens you — engage, do not avoid it.', zh: '摩擦激发成长。良性的竞争或热烈的争论会磨砺你——投入其中，别回避。', ja: '摩擦が成長を生む。健全な競争や活発な議論があなたを磨く——避けずに飛び込もう。' },
    reversed_text: { en: 'Needless conflict is draining everyone. Step back from the squabble and find the common goal.', zh: '无谓的冲突正消耗着每个人。从争吵中退开，去找到共同的目标。', ja: '不要な争いが皆を消耗させている。いさかいから一歩引き、共通の目標を見つけよう。' } },
  { id: 27, hue: 38, image_placeholder: '',
    card_name:     { en: 'Six of Wands', zh: '权杖六', ja: 'ワンドの6' },
    fortune_text:  { en: 'Victory and recognition arrive. Accept the applause — your effort has earned this moment in the sun.', zh: '胜利与赞誉到来。坦然接受掌声——你的努力赢得了这片高光时刻。', ja: '勝利と称賛が訪れる。拍手を受け取ろう——あなたの努力がこの晴れ舞台を勝ち取った。' },
    reversed_text: { en: 'Recognition is delayed or doubted. Validate yourself first; outside praise will follow your own conviction.', zh: '认可被推迟，或遭质疑。先肯定你自己；外界的赞美会随你的笃定而来。', ja: '評価が遅れるか、疑われている。まず自分を認めよう——外からの称賛は、あなたの確信の後に続く。' } },
  { id: 28, hue: 42, image_placeholder: '',
    card_name:     { en: 'Seven of Wands', zh: '权杖七', ja: 'ワンドの7' },
    fortune_text:  { en: "Stand your ground. You hold the higher position — defend what you've built with steady conviction.", zh: '坚守阵地。你占据着更高的位置——以沉稳的信念，守护你所建立的一切。', ja: '踏みとどまろう。あなたは高い位置にいる——築いてきたものを、揺るがぬ信念で守って。' },
    reversed_text: { en: 'Exhaustion is wearing down your defenses. Choose which battles truly deserve your strength.', zh: '疲惫正在磨蚀你的防线。挑出哪些战斗才真正配得上你的力气。', ja: '疲れが守りをすり減らしている。どの戦いが本当に力を注ぐ価値があるか選ぼう。' } },
  { id: 29, hue: 16, image_placeholder: '',
    card_name:     { en: 'Eight of Wands', zh: '权杖八', ja: 'ワンドの8' },
    fortune_text:  { en: 'Things move fast now. Messages, momentum, and swift progress — ride the speed and act without delay.', zh: '此刻一切都在飞速推进。讯息、势头与迅捷的进展——乘上这股速度，毫不迟疑地行动。', ja: '今、物事は速く動く。知らせ、勢い、素早い進展——その速度に乗り、ためらわず動こう。' },
    reversed_text: { en: 'Momentum scatters in too many directions. Slow down and realign before the rush leads nowhere.', zh: '势头散向了太多方向。在这股急冲沦为徒劳前，慢下来，重新对齐。', ja: '勢いが多方向へ散っている。焦りが空回りする前に、速度を落として整え直そう。' } },
  { id: 30, hue: 20, image_placeholder: '',
    card_name:     { en: 'Nine of Wands', zh: '权杖九', ja: 'ワンドの9' },
    fortune_text:  { en: "Weary but resilient, you're nearly there. Summon one last reserve of strength — the finish is close.", zh: '疲惫却坚韧，你已接近终点。唤起最后一分储备的力气——终线就在眼前。', ja: '疲れていても折れずに、あと少し。最後の力を呼び起こそう——ゴールは近い。' },
    reversed_text: { en: 'Defensiveness has become a wall. The fight may be over; lower your guard before it isolates you.', zh: '防备已筑成一堵墙。或许这场仗早已结束；在它把你孤立之前，放下戒备。', ja: '守りの姿勢が壁になっている。戦いはもう終わっているかも——孤立する前に警戒を解こう。' } },
  { id: 31, hue: 24, image_placeholder: '',
    card_name:     { en: 'Ten of Wands', zh: '权杖十', ja: 'ワンドの10' },
    fortune_text:  { en: 'You carry a heavy load. The burden is real, but the goal is near — set some weight down where you can.', zh: '你背负着沉重的担子。重负是真的，但目标已近——能放下的，就放下一些。', ja: '重い荷を背負っている。負担は本物だが、目標は近い——下ろせるものは下ろしていこう。' },
    reversed_text: { en: "You're carrying more than is yours. Delegate or release what was never your responsibility.", zh: '你扛着不属于你的东西。把那些本就不是你责任的，交出去或放下。', ja: '自分のものでない荷まで抱えている。もとから自分の責任でないものは、任せるか手放そう。' } },
  { id: 32, hue: 28, image_placeholder: '',
    card_name:     { en: 'Page of Wands', zh: '权杖侍从', ja: 'ワンドのペイジ' },
    fortune_text:  { en: 'A curious, eager spark. Explore a new passion freely — this is the time to play and discover.', zh: '一团好奇而热切的火苗。自由地去探索一份新的热情——此刻正适合玩耍与发现。', ja: '好奇心に満ちた、はやる火種。新しい情熱を自由に探ろう——今は遊び、見つける時。' },
    reversed_text: { en: 'Restless energy with no outlet. A scattered idea needs grounding before it fizzles.', zh: '躁动的能量找不到出口。一个散乱的点子需要落地，否则便会熄灭。', ja: '出口のない落ち着かないエネルギー。散らかった着想は、立ち消える前に地に足をつけよう。' } },
  { id: 33, hue: 32, image_placeholder: '',
    card_name:     { en: 'Knight of Wands', zh: '权杖骑士', ja: 'ワンドのナイト' },
    fortune_text:  { en: "Charge ahead with passion. Boldness and adventure favor you — just keep one eye on where you're charging.", zh: '带着热情向前冲。大胆与冒险都站在你这边——只是别忘了看一眼你冲向的方向。', ja: '情熱を胸に突き進もう。大胆さと冒険が味方する——ただ、突進する先にも目を向けて。' },
    reversed_text: { en: 'Impulsiveness outruns the plan. Temper the fire before haste turns into a setback.', zh: '冲动跑在了计划前头。在急躁酿成挫败之前，给火降降温。', ja: '衝動が計画を追い越している。焦りが失敗に変わる前に、火を抑えよう。' } },
  { id: 34, hue: 36, image_placeholder: '',
    card_name:     { en: 'Queen of Wands', zh: '权杖王后', ja: 'ワンドのクイーン' },
    fortune_text:  { en: 'Confident, warm, and magnetic. Lead with your radiant energy — others are drawn to your certainty.', zh: '自信、温暖、富有魅力。以你那耀眼的能量去引领——人们被你的笃定所吸引。', ja: '自信に満ち、温かく、人を惹きつける。輝くエネルギーで導こう——人はあなたの確かさに引き寄せられる。' },
    reversed_text: { en: 'Self-doubt dims your fire. Reconnect with what makes you feel bold and the warmth returns.', zh: '自我怀疑让你的火黯淡。重新连接那让你感到大胆的事物，温暖便会回来。', ja: '自己不信が火を曇らせる。自分を大胆にさせるものと再びつながれば、温もりは戻る。' } },
  { id: 35, hue: 40, image_placeholder: '',
    card_name:     { en: 'King of Wands', zh: '权杖国王', ja: 'ワンドのキング' },
    fortune_text:  { en: 'Visionary leadership is yours. Direct your bold energy with purpose and others will follow your lead.', zh: '富有远见的领导力属于你。带着目标去引导你那大胆的能量，众人自会追随。', ja: '先見のリーダーシップはあなたのもの。大胆なエネルギーを目的を持って導けば、人はついてくる。' },
    reversed_text: { en: 'Vision turns to impulsiveness or domineering. Lead by inspiring, not by forcing.', zh: '远见沦为了冲动或专横。以激励去引领，而非以强迫。', ja: 'ビジョンが衝動や横暴に変わっている。強制ではなく、鼓舞することで導こう。' } },

  // ── Cups (36–49) ──────────────────────────────────────────────────────
  { id: 36, hue: 200, image_placeholder: '',
    card_name:     { en: 'Ace of Cups', zh: '圣杯一', ja: 'カップのエース' },
    fortune_text:  { en: 'The heart overflows. A new love, friendship, or feeling arrives — open yourself to receive it fully.', zh: '心，满溢而出。一份新的爱、友谊或情感正到来——敞开自己，完整地接住它。', ja: '心が満ち溢れる。新しい愛・友情・感情が訪れる——自分を開いて、すべて受け取ろう。' },
    reversed_text: { en: 'Emotion is blocked or held back. Let yourself feel before the well runs dry.', zh: '情感被阻塞，或被压抑。在井水枯竭之前，允许自己去感受。', ja: '感情が塞がれ、抑えられている。泉が涸れる前に、感じることを自分に許そう。' } },
  { id: 37, hue: 204, image_placeholder: '',
    card_name:     { en: 'Two of Cups', zh: '圣杯二', ja: 'カップの2' },
    fortune_text:  { en: 'A meaningful connection forms. Mutual respect and affection flow both ways — honor this partnership.', zh: '一段有意义的连接正在形成。尊重与情意双向流动——珍视这份关系。', ja: '意味ある結びつきが生まれる。敬意と情が双方向に流れる——この絆を大切に。' },
    reversed_text: { en: 'A bond is out of balance or strained. Tend to the disconnect before it widens.', zh: '一段关系失了平衡，或绷得太紧。在裂隙扩大之前，去修补那份疏离。', ja: '絆のバランスが崩れ、張りつめている。隔たりが広がる前に手を入れよう。' } },
  { id: 38, hue: 208, image_placeholder: '',
    card_name:     { en: 'Three of Cups', zh: '圣杯三', ja: 'カップの3' },
    fortune_text:  { en: 'Friendship and celebration. Gather your people — joy multiplies when it is shared.', zh: '友谊与欢庆。把你的人聚到一起——喜悦在分享时会加倍。', ja: '友情と祝祭。仲間を集めよう——喜びは分かち合うほど膨らむ。' },
    reversed_text: { en: 'Overindulgence or social strain. Step back from the crowd and find quieter, truer company.', zh: '过度放纵，或社交的倦怠。从喧闹中退开，找回更安静、更真挚的陪伴。', ja: '度を越した享楽や、付き合いの疲れ。賑わいから離れ、静かで本物の交わりを。' } },
  { id: 39, hue: 212, image_placeholder: '',
    card_name:     { en: 'Four of Cups', zh: '圣杯四', ja: 'カップの4' },
    fortune_text:  { en: 'Contemplation and mild discontent. You may be overlooking a gift right in front of you — look up.', zh: '沉思，与淡淡的不满。你也许正忽略着眼前的一份礼物——抬起头看看。', ja: '物思いと、かすかな不満。目の前の贈り物を見落としているかも——顔を上げてみよう。' },
    reversed_text: { en: 'Apathy is lifting. A new openness lets you finally accept what is being offered.', zh: '倦怠正在消退。一份新的开放，让你终于能接受被给予的东西。', ja: '無気力が晴れていく。新たな開かれた心が、差し出されたものをようやく受け取らせる。' } },
  { id: 40, hue: 216, image_placeholder: '',
    card_name:     { en: 'Five of Cups', zh: '圣杯五', ja: 'カップの5' },
    fortune_text:  { en: "Grief over what spilled. Mourn what is lost, but turn around — two cups still stand behind you.", zh: '为洒落之物而悲伤。哀悼失去，但请转过身——你身后还立着两只杯子。', ja: 'こぼれたものを嘆く。失ったものを悼んでもいい、でも振り返って——背後にはまだ二つの杯が立っている。' },
    reversed_text: { en: 'Acceptance and recovery begin. You are ready to forgive and gather what remains.', zh: '接受与复原开始了。你已准备好原谅，并拾起仍留下的东西。', ja: '受け入れと回復が始まる。赦し、残されたものを拾い集める準備ができている。' } },
  { id: 41, hue: 220, image_placeholder: '',
    card_name:     { en: 'Six of Cups', zh: '圣杯六', ja: 'カップの6' },
    fortune_text:  { en: 'Sweet nostalgia and innocence. A reunion or fond memory warms you — let kindness lead.', zh: '甜美的怀旧与纯真。一次重逢或一段温馨的回忆温暖了你——让善意引路。', ja: '甘い郷愁と無垢。再会や懐かしい思い出があなたを温める——優しさに導かせよう。' },
    reversed_text: { en: 'Clinging to the past holds you back. Honor the memory, then return to the present.', zh: '对过去的紧抓拖住了你。致敬那段回忆，然后回到当下。', ja: '過去への執着が足を引っ張る。思い出を敬い、そして今に戻ろう。' } },
  { id: 42, hue: 224, image_placeholder: '',
    card_name:     { en: 'Seven of Cups', zh: '圣杯七', ja: 'カップの7' },
    fortune_text:  { en: 'So many options shimmer. Dream freely, but know which cup is real before you reach for it.', zh: '众多选项闪闪发光。尽情做梦，但在伸手之前，先认清哪只杯子是真的。', ja: 'いくつもの選択肢が揺らめく。自由に夢を見ても、手を伸ばす前にどの杯が本物か見極めて。' },
    reversed_text: { en: 'The fog clears. You can finally see through illusion and choose with clarity.', zh: '迷雾散去。你终于能看穿幻象，清明地做出选择。', ja: '霧が晴れる。幻を見抜き、明晰に選べるようになる。' } },
  { id: 43, hue: 198, image_placeholder: '',
    card_name:     { en: 'Eight of Cups', zh: '圣杯八', ja: 'カップの8' },
    fortune_text:  { en: 'Walk away from what no longer fulfills you. Leaving takes courage — a deeper calling waits ahead.', zh: '离开那些再也无法满足你的东西。离开需要勇气——前方有更深的召唤在等着。', ja: 'もう満たしてくれないものから歩き去ろう。去るには勇気がいる——その先で、より深い呼び声が待っている。' },
    reversed_text: { en: "You're caught between staying and going. Be honest about whether fear or love keeps you here.", zh: '你被困在去留之间。诚实地问问自己：留住你的，是恐惧还是爱。', ja: '留まるか去るかの間で揺れている。ここに留めているのは恐れか愛か、正直に見極めて。' } },
  { id: 44, hue: 202, image_placeholder: '',
    card_name:     { en: 'Nine of Cups', zh: '圣杯九', ja: 'カップの9' },
    fortune_text:  { en: "The wish card — contentment is yours. Savor this satisfaction; you've earned your moment of plenty.", zh: '心愿之牌——满足属于你。细细品味这份满意；这丰盈的时刻，是你应得的。', ja: '願いのカード——満ち足りはあなたのもの。この満足を味わおう——豊かなひとときは、あなたが勝ち取ったもの。' },
    reversed_text: { en: 'Pleasure feels hollow or smug. Look past surface comforts to what truly fulfills you.', zh: '快乐显得空洞，或带着自满。越过表层的舒适，去看真正能满足你的东西。', ja: '快楽が空虚か、独りよがりに感じる。表面的な心地よさの先に、本当に満たすものを見よう。' } },
  { id: 45, hue: 206, image_placeholder: '',
    card_name:     { en: 'Ten of Cups', zh: '圣杯十', ja: 'カップの10' },
    fortune_text:  { en: 'Lasting harmony and joy. Emotional fulfillment surrounds you — this is the happiness you hoped for.', zh: '长久的和谐与喜悦。情感的圆满环绕着你——这正是你曾期盼的幸福。', ja: '末永い調和と喜び。感情の充足があなたを包む——これこそ、望んでいた幸せ。' },
    reversed_text: { en: 'The picture of harmony hides a crack. Tend to the relationships beneath the ideal.', zh: '那幅和谐的画面藏着一道裂痕。去照看理想表象之下的那些关系。', ja: '調和の絵にひびが隠れている。理想の下にある関係に、手をかけよう。' } },
  { id: 46, hue: 210, image_placeholder: '',
    card_name:     { en: 'Page of Cups', zh: '圣杯侍从', ja: 'カップのペイジ' },
    fortune_text:  { en: 'A tender, creative message. Stay open to intuition and gentle surprises — the heart speaks softly.', zh: '一则温柔而富有创意的讯息。对直觉与温柔的惊喜保持开放——心，是轻声说话的。', ja: '優しく創造的な知らせ。直感とささやかな驚きに心を開いて——心は、そっと語りかける。' },
    reversed_text: { en: 'Emotional immaturity or a blocked muse. Let feelings flow without judging them.', zh: '情感上的不成熟，或被堵住的灵感。让情绪流动，别去评判它们。', ja: '感情の幼さや、塞がれた霊感。感情を裁かず、流れるに任せよう。' } },
  { id: 47, hue: 214, image_placeholder: '',
    card_name:     { en: 'Knight of Cups', zh: '圣杯骑士', ja: 'カップのナイト' },
    fortune_text:  { en: "A romantic, idealistic offer arrives. Follow the heart's invitation — but keep your feet on the ground.", zh: '一份浪漫而理想化的邀约到来。跟随内心的邀请——但双脚仍要踏在地上。', ja: 'ロマンチックで理想に満ちた誘いが届く。心の招きに従おう——ただし足は地につけて。' },
    reversed_text: { en: 'Charm masks moodiness or empty promises. Look for substance beneath the sentiment.', zh: '魅力之下，掩着喜怒无常或空头承诺。在情意背后，寻找真正的实质。', ja: '魅力が気分屋や口先の約束を覆い隠す。情の裏にある中身を見極めて。' } },
  { id: 48, hue: 218, image_placeholder: '',
    card_name:     { en: 'Queen of Cups', zh: '圣杯王后', ja: 'カップのクイーン' },
    fortune_text:  { en: 'Compassion and deep intuition. Trust your emotional wisdom — nurture others and yourself in equal measure.', zh: '慈悲，与深邃的直觉。信任你情感的智慧——以同等的分量去滋养他人与自己。', ja: '慈しみと深い直感。感情の知恵を信じて——人と自分を同じだけ慈しもう。' },
    reversed_text: { en: 'Emotions are overwhelming your boundaries. Refill your own cup before pouring for everyone else.', zh: '情绪正淹没你的边界。在为别人倾倒之前，先把自己的杯子斟满。', ja: '感情が境界を押し流している。皆に注ぐ前に、まず自分の杯を満たそう。' } },
  { id: 49, hue: 222, image_placeholder: '',
    card_name:     { en: 'King of Cups', zh: '圣杯国王', ja: 'カップのキング' },
    fortune_text:  { en: 'Emotional mastery and calm. Lead with empathy and a steady heart even when the waters churn.', zh: '对情感的驾驭，与从容。即使水面翻涌，也以同理心和沉稳的心去引领。', ja: '感情を治める落ち着き。水面が荒れても、共感と揺るがぬ心で導こう。' },
    reversed_text: { en: 'Suppressed feelings are leaking out as moodiness. Acknowledge the current beneath your composure.', zh: '被压抑的情感正以喜怒无常的方式渗出。承认你那份镇定之下的暗流。', ja: '抑え込んだ感情が、不機嫌として漏れ出ている。平静の下に流れる感情を認めよう。' } },

  // ── Swords (50–63) ────────────────────────────────────────────────────
  { id: 50, hue: 186, image_placeholder: '',
    card_name:     { en: 'Ace of Swords', zh: '宝剑一', ja: 'ソードのエース' },
    fortune_text:  { en: 'A breakthrough of clarity. Cut through confusion — a sharp new truth or idea hands you real power.', zh: '一次清明的突破。斩开困惑——一个锋利的新真相或新想法，递给你真正的力量。', ja: '明晰さの突破口。混乱を断ち切ろう——鋭い真実や着想が、本物の力を授ける。' },
    reversed_text: { en: 'Clouded thinking or misused words. Wait for clarity before you swing the blade.', zh: '混沌的思绪，或被误用的言辞。在挥剑之前，先等清明到来。', ja: '曇った思考や、誤って使われた言葉。剣を振るう前に、明晰さを待とう。' } },
  { id: 51, hue: 189, image_placeholder: '',
    card_name:     { en: 'Two of Swords', zh: '宝剑二', ja: 'ソードの2' },
    fortune_text:  { en: 'A stalemate demands a choice. Remove the blindfold; avoiding the decision only prolongs the tension.', zh: '僵局逼着你做选择。摘下蒙眼布吧；回避决定，只会让紧张拖得更久。', ja: '行き詰まりが選択を迫る。目隠しを外そう——決断を避けるほど、緊張は長引く。' },
    reversed_text: { en: 'The deadlock breaks. Information returns and you can finally choose a side.', zh: '僵局被打破。信息回来了，你终于能选定一边。', ja: '膠着が解ける。情報が戻り、ようやくどちらかを選べる。' } },
  { id: 52, hue: 192, image_placeholder: '',
    card_name:     { en: 'Three of Swords', zh: '宝剑三', ja: 'ソードの3' },
    fortune_text:  { en: 'Heartache cuts deep. Let the grief move through you — naming the pain is the first step to healing.', zh: '心痛，刺得很深。让悲伤流过你——为痛苦命名，是疗愈的第一步。', ja: '心の痛みが深く刺さる。悲しみを通り抜けさせよう——痛みに名前をつけることが、癒やしの第一歩。' },
    reversed_text: { en: 'The worst of the hurt is passing. Release the lingering resentment and let the wound close.', zh: '最深的伤痛正在过去。放下那残留的怨怼，让伤口愈合。', ja: '痛みの峠は越えつつある。残った恨みを手放し、傷を閉じさせよう。' } },
  { id: 53, hue: 195, image_placeholder: '',
    card_name:     { en: 'Four of Swords', zh: '宝剑四', ja: 'ソードの4' },
    fortune_text:  { en: 'Rest and recovery are required. Step back, breathe, and restore — the battle can wait for a rested mind.', zh: '休息与复原是必需的。退后、呼吸、恢复——战斗可以等一个休整好的头脑。', ja: '休息と回復が必要だ。退いて、息をつき、立て直そう——戦いは、休んだ心を待てる。' },
    reversed_text: { en: "It's time to re-enter the world. Prolonged retreat now turns rest into avoidance.", zh: '该重新走入世界了。此刻继续退缩，会让休息变成逃避。', ja: '世界へ戻る時。これ以上の引きこもりは、休息を逃避に変えてしまう。' } },
  { id: 54, hue: 198, image_placeholder: '',
    card_name:     { en: 'Five of Swords', zh: '宝剑五', ja: 'ソードの5' },
    fortune_text:  { en: 'A hollow victory. Winning at any cost has a price — consider whether this fight is worth the fallout.', zh: '一场空洞的胜利。不惜代价的赢，是有代价的——掂量这场仗是否值得它的余波。', ja: '虚しい勝利。なりふり構わぬ勝ちには代償がある——この戦いが、その後始末に見合うか考えて。' },
    reversed_text: { en: 'Reconciliation is possible. Lay down the blade and repair what conflict damaged.', zh: '和解是可能的。放下剑，去修补冲突所损坏的东西。', ja: '和解の余地がある。剣を置き、争いが壊したものを繕おう。' } },
  { id: 55, hue: 201, image_placeholder: '',
    card_name:     { en: 'Six of Swords', zh: '宝剑六', ja: 'ソードの6' },
    fortune_text:  { en: 'Moving toward calmer waters. Leave the turbulence behind — this transition leads somewhere gentler.', zh: '正驶向更平静的水域。把动荡留在身后——这次过渡通向更温和的地方。', ja: '穏やかな水域へ向かっている。波立ちを後にしよう——この移ろいは、もっと優しい場所へ続く。' },
    reversed_text: { en: "You're carrying old baggage into the new journey. Resolve what you keep dragging along.", zh: '你正把旧包袱带进新旅程。处理掉那些你一直拖着不放的东西。', ja: '古い荷物を新しい旅へ持ち込んでいる。引きずり続けているものに、けりをつけよう。' } },
  { id: 56, hue: 204, image_placeholder: '',
    card_name:     { en: 'Seven of Swords', zh: '宝剑七', ja: 'ソードの7' },
    fortune_text:  { en: 'Strategy over force. A clever, independent approach works — but make sure the cunning stays honest.', zh: '智取胜过强攻。一种巧妙而独立的方式行得通——但要确保机巧不越过诚实的界。', ja: '力より戦略。巧みで独立した手が効く——ただし、その狡知が正直さを超えないように。' },
    reversed_text: { en: "A deception is surfacing — yours or someone else's. Come clean before it unravels.", zh: '一桩欺瞒正在浮现——你的，或别人的。趁它尚未败露，坦白吧。', ja: '欺瞞が表に出てきている——自分のか、誰かのか。ほころびる前に、正直になろう。' } },
  { id: 57, hue: 188, image_placeholder: '',
    card_name:     { en: 'Eight of Swords', zh: '宝剑八', ja: 'ソードの8' },
    fortune_text:  { en: 'You feel trapped, but the bindings are looser than they look. The way out begins with one clear thought.', zh: '你觉得被困住了，但那些束缚比看上去松得多。出路，始于一个清晰的念头。', ja: '縛られていると感じても、その縄は見た目より緩い。出口は、一つの明晰な思考から始まる。' },
    reversed_text: { en: 'The blindfold slips. You are realizing the prison was self-made — and the door was never locked.', zh: '蒙眼布滑落了。你开始明白：这牢笼是自己造的——而门，从未上锁。', ja: '目隠しがずり落ちる。牢獄は自分で作ったもので、扉は最初から施錠されていなかったと気づく。' } },
  { id: 58, hue: 191, image_placeholder: '',
    card_name:     { en: 'Nine of Swords', zh: '宝剑九', ja: 'ソードの9' },
    fortune_text:  { en: "Anxiety looms in the dark. The fears feel huge at night; in daylight they shrink — you're stronger than the dread.", zh: '焦虑在黑暗里张牙舞爪。恐惧在夜里显得庞大；天一亮便会缩小——你比那份惊惧更强大。', ja: '不安が闇の中でふくらむ。恐れは夜には巨大に見え、昼には縮む——あなたは、その怯えより強い。' },
    reversed_text: { en: 'The nightmare is lifting. Sharing the worry out loud robs it of its power.', zh: '噩梦正在消散。把忧虑说出口，便夺去了它的力量。', ja: '悪夢が晴れていく。不安を声に出して分かち合えば、その力は奪われる。' } },
  { id: 59, hue: 194, image_placeholder: '',
    card_name:     { en: 'Ten of Swords', zh: '宝剑十', ja: 'ソードの10' },
    fortune_text:  { en: "A painful ending, but the worst is over. Rock bottom is solid ground — there's nowhere to go but up.", zh: '一个痛苦的结束，但最糟的已经过去。谷底是坚实的地面——除了向上，无处可去。', ja: '痛みを伴う終わり、でも最悪は過ぎた。どん底は固い地面——あとは上るだけ。' },
    reversed_text: { en: 'Recovery dawns after the low point. Resist replaying the defeat; the new day has already begun.', zh: '低谷之后，复原如破晓而来。别再回放那场失败；新的一天已经开始。', ja: 'どん底の後に回復が明ける。敗北を再生し続けないで——新しい一日はもう始まっている。' } },
  { id: 60, hue: 197, image_placeholder: '',
    card_name:     { en: 'Page of Swords', zh: '宝剑侍从', ja: 'ソードのペイジ' },
    fortune_text:  { en: 'Sharp curiosity and fresh ideas. Ask questions, gather truth — your alert mind is your advantage.', zh: '敏锐的好奇心，与崭新的想法。多发问、搜集真相——你那警觉的头脑就是你的优势。', ja: '鋭い好奇心と新しい着想。問いを立て、真実を集めよう——研ぎ澄まされた頭脳が、あなたの強み。' },
    reversed_text: { en: 'Scattered thoughts or careless words. Verify before you speak or act on the rumor.', zh: '散乱的思绪，或不慎的言语。在开口或听信传言行事之前，先去核实。', ja: '散らかった思考や、不用意な言葉。噂で語り動く前に、裏を取ろう。' } },
  { id: 61, hue: 200, image_placeholder: '',
    card_name:     { en: 'Knight of Swords', zh: '宝剑骑士', ja: 'ソードのナイト' },
    fortune_text:  { en: 'Charge ahead with focused intellect. Act decisively on your convictions — momentum favors the bold thinker.', zh: '以专注的思智向前冲。依着信念果断行动——势头偏爱敢想的人。', ja: '研ぎ澄ました知性で突き進もう。信念に従い決然と動こう——勢いは、大胆に考える者に味方する。' },
    reversed_text: { en: 'Haste and blunt words cause damage. Slow the charge before you cut what you meant to keep.', zh: '急躁与生硬的言辞会造成伤害。在你砍断本想留住的东西之前，放慢冲势。', ja: '性急さと無遠慮な言葉が傷をつくる。守りたいものを切る前に、突進を緩めよう。' } },
  { id: 62, hue: 203, image_placeholder: '',
    card_name:     { en: 'Queen of Swords', zh: '宝剑王后', ja: 'ソードのクイーン' },
    fortune_text:  { en: 'Clear-eyed and honest. Lead with sharp perception and fair judgment — truth is your kindness.', zh: '目光清澈，诚实坦荡。以敏锐的洞察与公正的判断去引领——真相，就是你的善意。', ja: '澄んだ目と正直さ。鋭い洞察と公正な判断で導こう——真実こそ、あなたの優しさ。' },
    reversed_text: { en: 'Coldness or harsh judgment creeps in. Let empathy soften the edge of your clarity.', zh: '冷漠或苛刻的评判悄然而入。让同理心，柔化你那份清醒的锋芒。', ja: '冷たさや厳しすぎる判断が忍び込む。共感で、明晰さの刃を和らげよう。' } },
  { id: 63, hue: 206, image_placeholder: '',
    card_name:     { en: 'King of Swords', zh: '宝剑国王', ja: 'ソードのキング' },
    fortune_text:  { en: 'Authority through reason. Decide with logic and integrity — your clear principles command respect.', zh: '以理性立威。用逻辑与正直去决断——你清晰的原则赢得敬重。', ja: '理性による権威。論理と誠実さで決断しよう——明確な原則が、敬意を集める。' },
    reversed_text: { en: 'Logic hardens into rigidity or controlling judgment. Lead with truth, not domination.', zh: '逻辑硬化成了僵固，或操控式的评判。以真相去引领，而非以压制。', ja: '論理が硬直や支配的な判断に変わっている。支配ではなく、真実で導こう。' } },

  // ── Pentacles (64–77) ─────────────────────────────────────────────────
  { id: 64, hue: 110, image_placeholder: '',
    card_name:     { en: 'Ace of Pentacles', zh: '星币一', ja: 'ペンタクルのエース' },
    fortune_text:  { en: 'A tangible new opportunity takes root. Plant this seed of prosperity — solid rewards grow from it.', zh: '一个实在的新机会扎下了根。种下这颗丰盛的种子——扎实的回报会由它长出。', ja: '確かな新しい好機が根を張る。豊かさの種を蒔こう——そこから着実な実りが育つ。' },
    reversed_text: { en: 'A missed chance or shaky plan. Check the foundation before you invest further.', zh: '一个错失的机会，或不稳的计划。在投入更多之前，检查根基。', ja: '逃した好機か、ぐらついた計画。さらに投じる前に、土台を確かめよう。' } },
  { id: 65, hue: 114, image_placeholder: '',
    card_name:     { en: 'Two of Pentacles', zh: '星币二', ja: 'ペンタクルの2' },
    fortune_text:  { en: 'Juggling priorities with grace. Stay flexible — you can balance the demands if you keep things moving.', zh: '优雅地兼顾多重要务。保持灵活——只要让事情持续流转，你就能平衡这些需求。', ja: '優先事項を軽やかにやりくりする。柔軟でいよう——流れを止めなければ、要求のバランスは取れる。' },
    reversed_text: { en: 'Too many balls in the air. Something will drop unless you simplify and prioritize.', zh: '抛在空中的球太多了。若不精简并排序，总会有东西落地。', ja: '空中に投げた球が多すぎる。整理して優先順位をつけないと、何かを落とす。' } },
  { id: 66, hue: 118, image_placeholder: '',
    card_name:     { en: 'Three of Pentacles', zh: '星币三', ja: 'ペンタクルの3' },
    fortune_text:  { en: 'Collaboration builds something lasting. Bring your skill to the team — shared craftsmanship pays off.', zh: '协作铸就长久之物。把你的技艺带进团队——共同的匠心终有回报。', ja: '協働が、長く続くものを築く。技をチームに持ち寄ろう——分かち合う職人技は報われる。' },
    reversed_text: { en: 'Misaligned effort or unrecognized work. Clarify roles before the project stalls.', zh: '努力错位，或付出无人认可。在项目停滞之前，理清各自的角色。', ja: 'かみ合わない努力や、認められない仕事。プロジェクトが滞る前に、役割を明確に。' } },
  { id: 67, hue: 122, image_placeholder: '',
    card_name:     { en: 'Four of Pentacles', zh: '星币四', ja: 'ペンタクルの4' },
    fortune_text:  { en: "Security through careful holding. Protect what you've built — but make sure saving doesn't become clutching.", zh: '以谨慎的持守换来安稳。守护你所建立的——但别让储蓄变成紧攥不放。', ja: '慎重に守ることで得る安定。築いたものを守ろう——ただし、蓄えが「抱え込み」にならぬように。' },
    reversed_text: { en: 'A grip held too tight loosens. Loosen control over money or status and energy flows again.', zh: '攥得太紧的手，正在松开。松一松对金钱或地位的掌控，能量便会重新流动。', ja: '握りしめ過ぎた手が緩む。お金や地位への執着を緩めれば、エネルギーは再び流れる。' } },
  { id: 68, hue: 126, image_placeholder: '',
    card_name:     { en: 'Five of Pentacles', zh: '星币五', ja: 'ペンタクルの5' },
    fortune_text:  { en: 'Hardship and a feeling of lack. Help is nearer than it seems — look for the lit window, and ask.', zh: '困顿，与匮乏之感。援助比看上去更近——寻找那扇亮着灯的窗，然后开口求助。', ja: '苦境と、欠乏の感覚。助けは思うより近い——灯のともる窓を探し、声をかけよう。' },
    reversed_text: { en: 'Recovery from hard times begins. Support arrives and stability slowly returns.', zh: '从艰难中复原，已经开始。支援到来，稳定缓缓归来。', ja: '苦しい時期からの回復が始まる。支えが届き、安定が少しずつ戻る。' } },
  { id: 69, hue: 130, image_placeholder: '',
    card_name:     { en: 'Six of Pentacles', zh: '星币六', ja: 'ペンタクルの6' },
    fortune_text:  { en: 'Generosity flows both ways. Give and receive fairly — balanced exchange strengthens everyone involved.', zh: '慷慨双向流动。公平地给予与接受——平衡的交换让所有人都更稳固。', ja: '寛大さは双方向に流れる。公平に与え、受け取ろう——釣り合った交換が、関わる皆を強くする。' },
    reversed_text: { en: 'Strings attached to giving, or uneven debts. Examine the power balance in who owes whom.', zh: '给予附着了条件，或债务并不对等。审视一下“谁欠谁”背后的权力天平。', ja: '見返り付きの施しや、偏った貸し借り。「誰が誰に負うか」の力関係を見直そう。' } },
  { id: 70, hue: 134, image_placeholder: '',
    card_name:     { en: 'Seven of Pentacles', zh: '星币七', ja: 'ペンタクルの7' },
    fortune_text:  { en: 'Patience with a long-term investment. Your effort is growing — tend it steadily and let it ripen.', zh: '对长期投入保持耐心。你的努力正在生长——稳稳地照料，让它成熟。', ja: '長期の投資には忍耐を。努力は育っている——着実に手入れし、熟すのを待とう。' },
    reversed_text: { en: 'Impatience or wasted effort. Reassess whether this is worth more of your time.', zh: '焦躁，或被浪费的努力。重新评估：这是否还值得你投入更多时间。', ja: '焦りや、無駄になった労力。これ以上の時間を注ぐ価値があるか見直そう。' } },
  { id: 71, hue: 112, image_placeholder: '',
    card_name:     { en: 'Eight of Pentacles', zh: '星币八', ja: 'ペンタクルの8' },
    fortune_text:  { en: 'Devotion to your craft. Diligent, focused work compounds — mastery is built one careful repetition at a time.', zh: '对手艺的专注奉献。勤勉而专注的工作会累积——精通，是一次次细致的重复堆出来的。', ja: '技への献身。勤勉で集中した仕事は積み重なる——熟達は、丁寧な反復の一つひとつで築かれる。' },
    reversed_text: { en: 'Going through the motions, or perfectionism stalling you. Reconnect with why the work matters.', zh: '流于形式地应付，或被完美主义卡住。重新连接“这份工作为何重要”。', ja: '形だけこなしているか、完璧主義で足踏みしている。なぜこの仕事が大切かと、もう一度つながろう。' } },
  { id: 72, hue: 116, image_placeholder: '',
    card_name:     { en: 'Nine of Pentacles', zh: '星币九', ja: 'ペンタクルの9' },
    fortune_text:  { en: "Self-made comfort and independence. Enjoy the fruits of your discipline — you've cultivated this abundance.", zh: '凭己之力赢得的安逸与独立。享受自律结出的果实——这份丰盛，是你亲手栽培的。', ja: '自ら築いた安らぎと自立。自律の実りを味わおう——この豊かさは、あなたが育てたもの。' },
    reversed_text: { en: 'Comfort built on overwork, or shaky finances. Rebalance effort and genuine enjoyment.', zh: '建立在过劳之上的安逸，或并不稳的财务。重新平衡付出与真正的享受。', ja: '働きすぎの上の安楽や、ぐらつく家計。努力と、心からの楽しみのバランスを取り直そう。' } },
  { id: 73, hue: 120, image_placeholder: '',
    card_name:     { en: 'Ten of Pentacles', zh: '星币十', ja: 'ペンタクルの10' },
    fortune_text:  { en: 'Lasting wealth and legacy. Long-term security and family stability are within reach — build for the future.', zh: '长久的财富与传承。长远的保障与家庭的稳定触手可及——为未来而建造。', ja: '末永い富と継承。長期の安定と家族の安らぎが手の届くところに——未来のために築こう。' },
    reversed_text: { en: 'A financial or family foundation needs tending. Do not take long-term security for granted.', zh: '财务或家庭的根基需要打理。别把长远的安稳视作理所当然。', ja: '財や家庭の土台に手入れが要る。長期の安定を当たり前と思わないで。' } },
  { id: 74, hue: 124, image_placeholder: '',
    card_name:     { en: 'Page of Pentacles', zh: '星币侍从', ja: 'ペンタクルのペイジ' },
    fortune_text:  { en: 'A studious new beginning. Commit to learning a practical skill — small steady steps build real results.', zh: '一个勤学的新开端。投入去学一门实用的技能——稳健的小步，累出真实的成果。', ja: '学びに満ちた新たな始まり。実用的な技能を学ぶと決めよう——着実な小さな一歩が、本物の成果を築く。' },
    reversed_text: { en: 'Procrastination or unrealistic plans. Ground the ambition in a concrete first step.', zh: '拖延，或不切实际的计划。把雄心落到一个具体的第一步上。', ja: '先延ばしや、現実離れした計画。野心を、具体的な第一歩に落とし込もう。' } },
  { id: 75, hue: 128, image_placeholder: '',
    card_name:     { en: 'Knight of Pentacles', zh: '星币骑士', ja: 'ペンタクルのナイト' },
    fortune_text:  { en: 'Steady, reliable progress. Methodical effort wins — keep plodding and the work gets done right.', zh: '稳健而可靠的进展。有条不紊的努力终会取胜——一步步踏实走，事情就会做得妥帖。', ja: '着実で頼もしい歩み。地道な努力が勝つ——こつこつ続ければ、仕事はきちんと仕上がる。' },
    reversed_text: { en: 'Routine has turned to stagnation. Add a little flexibility before the diligence becomes a rut.', zh: '常规已变成停滞。在勤勉沦为一成不变之前，添一点灵活。', ja: 'ルーティンが停滞に変わっている。勤勉がマンネリになる前に、少しの柔軟さを。' } },
  { id: 76, hue: 132, image_placeholder: '',
    card_name:     { en: 'Queen of Pentacles', zh: '星币王后', ja: 'ペンタクルのクイーン' },
    fortune_text:  { en: 'Nurturing and resourceful. Care for home, work, and self with practical warmth — abundance grows from grounded love.', zh: '体贴而善于经营。以务实的温暖照料家庭、工作与自己——丰盛，从脚踏实地的爱中生长。', ja: '慈しみ深く、機転が利く。実用的な温かさで、家庭・仕事・自分を世話しよう——豊かさは、地に足のついた愛から育つ。' },
    reversed_text: { en: 'Spread too thin between giving and providing. Restore your own security before tending everyone else.', zh: '在给予与供养之间被摊得太薄。在照顾所有人之前，先恢复你自己的安稳。', ja: '与えることと支えることの間で、手いっぱいになっている。皆を世話する前に、まず自分の安定を取り戻そう。' } },
  { id: 77, hue: 136, image_placeholder: '',
    card_name:     { en: 'King of Pentacles', zh: '星币国王', ja: 'ペンタクルのキング' },
    fortune_text:  { en: 'Abundant, grounded leadership. Manage your resources with discipline and generosity — lasting prosperity follows.', zh: '丰盛而脚踏实地的领导力。以自律与慷慨去管理你的资源——长久的繁荣随之而来。', ja: '豊かで、地に足のついたリーダーシップ。自律と寛大さで資源を治めよう——末永い繁栄が続く。' },
    reversed_text: { en: 'Material focus tips into greed or stubborn control. Remember wealth is a tool, not the goal.', zh: '对物质的专注，倾向了贪婪或固执的掌控。记住：财富是工具，而非目的。', ja: '物質への偏りが、強欲や頑なな支配に傾く。富は道具であって、目的ではないと思い出して。' } },
]
