<script setup lang="ts">
/**
 * TarotCard — in-pet tarot overlay (Major Arcana single draw).
 *
 * Rendered inside the main pet window (not a separate OS window) so it feels
 * integrated, like the right-click bubble menu. PetWindow grows the window to
 * a card-suitable size (scaled by the 大中小 character setting) and hides the
 * pet sprite while this is open, then restores both on close.
 *
 * Styling matches the app's frosted-green glass palette (see ChatBubble /
 * ContextMenu). The card faces themselves are placeholder SVGs generated by
 * scripts/gen-tarot-cards.mjs and referenced via TAROT_ASSETS — swap those
 * files (and TAROT_ASSETS.audio) for real art / audio later; no logic changes.
 *
 * Flow: entrance (slide+fade+scale) → click to flip (3D Y-axis, repeat clicks
 * blocked mid-flip) → "interpreting" delay (1–2 s) → reveal card name + fortune
 * with a pure-CSS glow + code-positioned particle burst → Redraw / Close.
 *
 * The root carries `pet-ui-overlay` so the per-pixel hit-test keeps the window
 * interactive while the reading is open.
 */
import { ref, computed } from 'vue'
import {
  TAROT_DECK, TAROT_ASSETS, TAROT_TIMINGS, type TarotCard, type LocalizedText,
} from '../config/tarot'
import { useI18n } from '../i18n'
import { playDrawSound, playFlipSound } from '../composables/useTarotSound'

const emit = defineEmits<{ close: [] }>()

const { t, locale } = useI18n()
/** Pick the active-locale string from a LocalizedText field. */
const L = (txt: LocalizedText): string => txt[locale.value]

// ── State ───────────────────────────────────────────────────────────────
const visible    = ref(false)
const card       = ref<TarotCard>(TAROT_DECK[0])
const reversed   = ref(false)   // true = card drawn inverted (50 % chance)
const flipped    = ref(false)
const isFlipping = ref(false)
const loading    = ref(false)
const revealed   = ref(false)
const drawKey    = ref(0)

let loadingTimer: ReturnType<typeof setTimeout> | null = null

// Active interpretation: orientation × locale.
const fortuneText = computed(() =>
  L(reversed.value ? card.value.reversed_text : card.value.fortune_text),
)
// Localized card name for the active locale.
const cardName = computed(() => L(card.value.card_name))

// ── Card visuals (SVG image with gradient fallback) ─────────────────────
function frontImage(c: TarotCard): string {
  return c.image_placeholder || TAROT_ASSETS.cardFrontImage(c.id)
}

const frontStyle = computed(() => {
  const img = frontImage(card.value)
  const base = img
    ? { backgroundImage: `url("${img}")` }
    : (() => {
        const h = card.value.hue
        return { backgroundImage: `linear-gradient(150deg, hsl(${h} 70% 62%), hsl(${(h + 40) % 360} 65% 42%))` }
      })()
  // Reversed cards are displayed rotated 180° on the front face.
  return reversed.value ? { ...base, transform: 'rotateY(180deg) rotate(180deg)' } : base
})

const backStyle = computed(() =>
  TAROT_ASSETS.cardBackImage
    ? { backgroundImage: `url("${TAROT_ASSETS.cardBackImage}")` }
    : { backgroundImage: 'linear-gradient(160deg, #dff0df, #a9cda9)' },
)

// ── Particles (pure code, no textures) ──────────────────────────────────
interface Particle { tx: number; ty: number; delay: number; size: number; hue: number }
const particles = ref<Particle[]>([])

function spawnParticles(): void {
  const n = 16
  const out: Particle[] = []
  for (let i = 0; i < n; i++) {
    const angle = (Math.PI * 2 * i) / n + Math.random() * 0.4
    const dist  = 60 + Math.random() * 70
    out.push({
      tx:    Math.cos(angle) * dist,
      ty:    Math.sin(angle) * dist,
      delay: Math.random() * 0.22,
      size:  3 + Math.random() * 4,
      hue:   card.value.hue + (Math.random() * 40 - 20),
    })
  }
  particles.value = out
}

// ── Draw / reset ────────────────────────────────────────────────────────
function pickRandomCard(): TarotCard {
  return TAROT_DECK[Math.floor(Math.random() * TAROT_DECK.length)]
}

function resetToFaceDown(): void {
  if (loadingTimer) { clearTimeout(loadingTimer); loadingTimer = null }
  flipped.value    = false
  isFlipping.value = false
  loading.value    = false
  revealed.value   = false
  particles.value  = []
  card.value       = pickRandomCard()
  reversed.value   = Math.random() < 0.5   // 50 % chance of reversed orientation
  drawKey.value++          // remount stage → entrance animation replays
  playDrawSound()
}

// ── Flip interaction ────────────────────────────────────────────────────
function onCardClick(): void {
  if (isFlipping.value || flipped.value) return   // ignore mid-flip / when shown

  playFlipSound()
  isFlipping.value = true
  flipped.value    = true
  loading.value    = true

  const { loadingMinMs, loadingMaxMs } = TAROT_TIMINGS
  const delay = loadingMinMs + Math.random() * (loadingMaxMs - loadingMinMs)
  loadingTimer = setTimeout(() => {
    loading.value    = false
    revealed.value   = true
    isFlipping.value = false
    spawnParticles()
    loadingTimer = null
  }, delay)
}

// When dismissing, skip the overlay's leave fade: PetWindow shrinks the window
// back first, so a fade here would play at the pet's original spot and look
// like a ghost card fading out. Removing instantly hard-cuts straight to the pet.
const skipLeave = ref(false)

// ── Public API (called by PetWindow) ────────────────────────────────────
function open(): void {
  skipLeave.value = false   // fade the overlay IN on open
  visible.value = true
  resetToFaceDown()
}
/** User-initiated close request — PetWindow orchestrates the shrink + fade. */
function requestClose(): void {
  emit('close')
}
/**
 * Unmount the overlay instantly (no leave fade). PetWindow calls this AFTER it
 * has shrunk the window back, so there is no card lingering/fading at the pet's
 * original position.
 */
function dismiss(): void {
  if (loadingTimer) { clearTimeout(loadingTimer); loadingTimer = null }
  skipLeave.value = true
  visible.value = false
}
defineExpose({ open, dismiss })
</script>

<template>
  <Transition name="tarot-fade" :css="!skipLeave">
    <div v-if="visible" class="tarot-overlay pet-ui-overlay" @click.self="requestClose">
      <!-- Controls -->
      <div class="tarot-controls">
        <button class="ctrl" :disabled="isFlipping" :title="t.tarot.redraw" @click.stop="resetToFaceDown">↻</button>
        <button class="ctrl" :title="t.tarot.close" @click.stop="requestClose">×</button>
      </div>

      <!-- Card stage (keyed → entrance animation replays on each draw) -->
      <div :key="drawKey" class="stage">
        <div
          class="card"
          :class="{ 'is-flipped': flipped, 'is-glowing': revealed, 'is-locked': isFlipping }"
          :style="{ '--hue': card.hue }"
          role="button"
          @click="onCardClick"
        >
          <div class="card-inner">
            <div class="face back"  :style="backStyle" />
            <div class="face front" :style="frontStyle" />
          </div>
          <span
            v-for="(p, i) in particles"
            :key="i"
            class="particle"
            :style="{
              '--tx': p.tx + 'px', '--ty': p.ty + 'px',
              '--delay': p.delay + 's', '--size': p.size + 'px',
              background: `hsl(${p.hue} 90% 68%)`,
            }"
          />
        </div>
      </div>

      <!-- Readout -->
      <div class="readout">
        <Transition name="tarot-fade" mode="out-in">
          <div v-if="loading" key="load" class="loading">
            <span class="dot" /><span class="dot" /><span class="dot" />
            <span class="loading-text">{{ t.tarot.interpreting }}</span>
          </div>
          <div v-else-if="revealed" key="res" class="result">
            <div class="result-title">
              {{ cardName }}
              <span class="result-orientation" :class="reversed ? 'is-reversed' : 'is-upright'">
                {{ reversed ? t.tarot.reversed : t.tarot.upright }}
              </span>
            </div>
            <p class="result-text">{{ fortuneText }}</p>
          </div>
          <div v-else key="hint" class="hint">{{ t.tarot.hint }}</div>
        </Transition>
      </div>
    </div>
  </Transition>
</template>

<style scoped>
/* ── Overlay (transparent backdrop; floats over the desktop) ─────────── */
.tarot-overlay {
  position: fixed;
  inset: 0;
  z-index: 1000;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 12px;
  padding: 14px 12px 12px;
  box-sizing: border-box;
  font-family: system-ui, "Segoe UI", "Noto Sans SC", "Noto Sans JP", sans-serif;
  user-select: none;
}

/* ── Controls ───────────────────────────────────────────────────────── */
.tarot-controls {
  position: absolute;
  top: 8px;
  right: 8px;
  display: flex;
  gap: 6px;
}
.ctrl {
  width: 26px;
  height: 26px;
  border-radius: 50%;
  border: 1px solid rgba(119, 153, 119, 0.40);
  background: rgba(245, 250, 245, 0.92);
  backdrop-filter: blur(16px) saturate(150%);
  -webkit-backdrop-filter: blur(16px) saturate(150%);
  color: #2a4a2a;
  font-size: 15px;
  line-height: 1;
  cursor: pointer;
  box-shadow: 0 2px 8px rgba(40, 70, 40, 0.14);
  transition: background 150ms ease, transform 120ms ease, opacity 150ms ease;
}
.ctrl:hover:not(:disabled)  { background: #fff; transform: scale(1.08); }
.ctrl:active:not(:disabled) { transform: scale(0.92); }
.ctrl:disabled { opacity: 0.4; cursor: not-allowed; }

/* ── Card stage + entrance animation ────────────────────────────────── */
.stage {
  perspective: 1100px;
  animation: card-enter 560ms cubic-bezier(0.22, 1, 0.36, 1) both;
}
@keyframes card-enter {
  from { opacity: 0; transform: translateY(60px) scale(0.82); }
  to   { opacity: 1; transform: translateY(0)    scale(1);    }
}

.card {
  position: relative;
  height: 56vh;
  aspect-ratio: 300 / 500;
  cursor: pointer;
  transition: transform 200ms ease;
}
.card:not(.is-flipped):hover { transform: translateY(-5px); }
.card.is-flipped { cursor: default; }
.card.is-locked  { pointer-events: none; }

.card-inner {
  position: relative;
  width: 100%;
  height: 100%;
  transform-style: preserve-3d;
  transition: transform v-bind('TAROT_TIMINGS.flipMs + "ms"') cubic-bezier(0.45, 0, 0.25, 1);
  border-radius: 16px;
}
.card.is-flipped .card-inner { transform: rotateY(180deg); }

.face {
  position: absolute;
  inset: 0;
  border-radius: 16px;
  backface-visibility: hidden;
  -webkit-backface-visibility: hidden;
  background-size: cover;
  background-position: center;
  box-shadow: 0 10px 28px rgba(40, 70, 40, 0.30);
  border: 1px solid rgba(255, 255, 255, 0.5);
}
.back  { transform: rotateY(0deg); }
.front { transform: rotateY(180deg); }

/* ── Glow VFX (pure box-shadow) ─────────────────────────────────────── */
.card.is-glowing .card-inner { animation: glow-pulse 2.4s ease-in-out infinite; }
@keyframes glow-pulse {
  0%, 100% { box-shadow: 0 0 12px 2px hsl(var(--hue) 85% 62% / 0.45), 0 0 26px 6px hsl(var(--hue) 85% 60% / 0.22); }
  50%      { box-shadow: 0 0 20px 5px hsl(var(--hue) 90% 68% / 0.70), 0 0 46px 13px hsl(var(--hue) 85% 60% / 0.40); }
}

/* ── Particles ──────────────────────────────────────────────────────── */
.particle {
  position: absolute;
  top: 50%;
  left: 50%;
  width: var(--size);
  height: var(--size);
  border-radius: 50%;
  pointer-events: none;
  opacity: 0;
  box-shadow: 0 0 6px 1px currentColor;
  animation: particle-fly 1000ms ease-out var(--delay) forwards;
}
@keyframes particle-fly {
  0%   { opacity: 0;   transform: translate(-50%, -50%) scale(0.4); }
  20%  { opacity: 1; }
  100% { opacity: 0;   transform: translate(calc(-50% + var(--tx)), calc(-50% + var(--ty))) scale(1); }
}

/* ── Readout (frosted-green, matches ChatBubble) ────────────────────── */
.readout {
  width: min(94%, 340px);
  min-height: 54px;
  display: flex;
  align-items: center;
  justify-content: center;
}
.hint { color: rgba(42, 74, 42, 0.7); font-size: 12px; text-align: center; }

.loading {
  display: flex; align-items: center; gap: 6px;
  padding: 7px 14px;
  background: rgba(245, 250, 245, 0.92);
  border: 1px solid rgba(148, 185, 148, 0.45);
  border-radius: 999px;
  color: #2a4a2a; font-size: 12.5px;
  box-shadow: 0 2px 8px rgba(40, 70, 40, 0.12);
}
.dot { width: 6px; height: 6px; border-radius: 50%; background: currentColor; animation: dot-bounce 1s ease-in-out infinite; }
.dot:nth-child(2) { animation-delay: 0.15s; }
.dot:nth-child(3) { animation-delay: 0.30s; }
@keyframes dot-bounce {
  0%, 80%, 100% { transform: translateY(0);    opacity: 0.4; }
  40%           { transform: translateY(-5px); opacity: 1; }
}

.result {
  width: 100%;
  box-sizing: border-box;
  max-height: 26vh;
  overflow-y: auto;
  background: rgba(245, 250, 245, 0.94);
  border: 1px solid rgba(148, 185, 148, 0.45);
  border-radius: 14px;
  padding: 11px 14px;
  backdrop-filter: blur(20px) saturate(160%);
  -webkit-backdrop-filter: blur(20px) saturate(160%);
  box-shadow: 0 4px 14px rgba(40, 70, 40, 0.16), inset 0 1px 0 rgba(255, 255, 255, 0.8);
}
.result-title {
  font-family: Georgia, "Times New Roman", serif;
  font-size: 15px; font-weight: 700; color: #1a2e1a;
  margin-bottom: 5px; text-align: center;
  display: flex; align-items: center; justify-content: center; gap: 7px; flex-wrap: wrap;
}
.result-orientation {
  font-family: system-ui, "Segoe UI", sans-serif;
  font-size: 10px; font-weight: 600; letter-spacing: 0.06em;
  padding: 2px 7px; border-radius: 999px;
}
.result-orientation.is-upright {
  background: rgba(86, 153, 86, 0.15); color: #2a6a2a;
  border: 1px solid rgba(86, 153, 86, 0.35);
}
.result-orientation.is-reversed {
  background: rgba(153, 86, 86, 0.13); color: #6a2a2a;
  border: 1px solid rgba(153, 86, 86, 0.30);
}
.result-text {
  margin: 0;
  font-size: 12px; line-height: 1.55; color: #1a2e1a;
  word-break: break-word; overflow-wrap: anywhere;
}

/* ── Transitions ────────────────────────────────────────────────────── */
.tarot-fade-enter-active, .tarot-fade-leave-active { transition: opacity 220ms ease; }
.tarot-fade-enter-from,  .tarot-fade-leave-to      { opacity: 0; }
</style>
